---
author      : Patrick Toche
framework   : bootstrap  # minimal, io2012, html5slides, shower, dzslides
hitheme     : solarized_light  # tomorrow, solarized_light
mode        : selfcontained  # selfcontained, standalone, draft
url         : {lib: "../libraries", assets: "../assets"}
--- 


#### Exercises to Accompany Thomas Piketty's *Capital in the 21st Century* (Harvard University Press, 2014)

Documents needed for practice exercises will be listed here as they become available. 

<br>

#### Chapter 2 

The 'Law Of Cumulated Growth' &mdash; Reproduce Table 2-2:

<a href="Growth/Table 2-2 - Law Of Cumulated Growth.xls">Hints [xls]</a>

#### Chapter 7 

Graph a Lorenz curve and compute a Gini coefficient:

<a href="Distribution/Lorenz-Gini/Lorenz-Gini.pdf">Instructions [pdf]</a>

<a href="Distribution/Lorenz-Gini/Lorenz-Gini.xls">Hints [xls]</a>

<a href="Distribution/Lorenz-Gini/Lorenz-Gini.R">Code [R]</a>

<a href="Distribution/Lorenz-Gini/Lorenz-chart.pdf">Chart [pdf]</a>

#### Chapter 9

Analyze the distribution of top incomes among professional athletes using publicly reported salaries and earnings.

<a href="Distribution/DistributionOfSalaries/Instructions.pdf">Instructions [pdf]</a>

<a href="Distribution/DistributionOfSalaries/DistributionOfSalaries.xls">Hints [xls]</a>

<a href="Distribution/DistributionOfSalaries/DistributionOfSalaries.R">Code [R]</a>

**Examples of charts produced by the R code (worst example on the left, best example on the right):**

<a href="Distribution/DistributionOfSalaries/01-linechart-with-multiple-problems.pdf">Chart 1 [pdf]</a> 
; 
<a href="Distribution/DistributionOfSalaries/02-barchart-vertical-unsorted-unformatted.pdf">Chart 2 [pdf]</a> 
; 
<a href="Distribution/DistributionOfSalaries/03-barchart-vertical-descending.pdf">Chart 3 [pdf]</a> 
; 
<a href="Distribution/DistributionOfSalaries/04-barchart-vertical-ascending.pdf">Chart 4 [pdf]</a> ; 
<a href="Distribution/DistributionOfSalaries/05-barchart-horizontal-descending.pdf">Chart 5 [pdf]</a> 
;
<a href="Distribution/DistributionOfSalaries/06-barchart-horizontal-ascending.pdf">Chart 6 [pdf]</a> 
; 
<a href="Distribution/DistributionOfSalaries/07-barchart-horizontal-ascending-colors.pdf">Chart 7 [pdf]</a> 
; 
<a href="Distribution/DistributionOfSalaries/08-barchart-horizontal-ascending-set1.pdf">Chart 8 [pdf]</a> 
; 
<a href="Distribution/DistributionOfSalaries/09-barchart-horizontal-ascending-blues.pdf">Chart 9 [pdf]</a>
; 
<a href="Distribution/DistributionOfSalaries/10-barchart-horizontal-ascending-gradient-blues.pdf">Chart 10 [pdf]</a>
; 
<a href="Distribution/DistributionOfSalaries/11-barchart-horizontal-ascending-gradient-reds.pdf">Chart 11 [pdf]</a> 
; 
<a href="Distribution/DistributionOfSalaries/12-barchart-Real-Madrid.pdf">Chart 12 [pdf]</a>


#### Chapter 11

Analyze the distribution of wealth using the Forbes magazine billionaires lists.

<a href="Distribution/DistributionOfWealth/Instructions.pdf">Instructions [pdf]</a>

<a href="Distribution/DistributionOfWealth/forbes-1996.xls">Forbes / 1996 [xls]</a>

<a href="Distribution/DistributionOfWealth/forbes-2014.xls">Forbes / 2014 [xls]</a>

<a href="Distribution/DistributionOfWealth/cpi.xls">CPI / United States Dollar Consumer Price Index [xls]</a>

<a href="Distribution/DistributionOfWealth/DistributionOfWealth.xls">Hints [xls]</a>

