---
title       : Chapter 15 -- A Global Tax on Capital
subtitle    : Thomas Piketty, Capital in the 21st Century (Harvard University Press 2014)
author      : Patrick Toche
framework   : io2012  # minimal, io2012, html5slides, shower, dzslides
mode        : selfcontained  # selfcontained, standalone, draft
widgets     : mathjax   # [mathjax, quiz, bootstrap]
ext_widgets : {rCharts: [libraries/nvd3]}  # libraries/morris, libraries/highcharts, libraries/rickshaw, libraries/dimple
url         : {lib: "../../libraries", assets: "../../assets"}
lecnum      : "15"
--- {class: cover-slide}

```{r 'preamble', message = FALSE, warning = FALSE, error = FALSE, echo = FALSE, tidy = FALSE, comment = NA, cache = FALSE}
require(knitr)
library(png)   # to display external png and control dimensions
library(grid)  # to display external png and control dimensions
opts_chunk$set(echo = FALSE, cache = FALSE)
source('../../shared/shared.R')
```

---

### Introduction  

- This set of slides surveys selected topics from *Capital in the Twenty-First Century*, a book written by economist Thomas Piketty, published in English in 2014 to great acclaim.
- All source files for this course are available for download by anyone without restrictions at https://github.com/ptoche/piketty
- The full course is expected to be completed by April 2015.
- Chapter 14 examined the structure of taxes and other government revenues.
- Chapter 15 considers a global tax on capital.

---

To regulate the globalized patrimonial capitalism of the twenty-first century, rethinking the twentieth-century fiscal and social model and adapting it to today’s world will not be enough. To be sure, appropriate updating of the last century’s social-democratic and fiscal-liberal program is essential, as I tried to show in the previous two chapters, which focused on two fundamental institu- tions that were invented in the twentieth century and must continue to play a central role in the future: the social state and the progressive income tax. But if democracy is to regain control over the globalized financial capitalism of this century, it must also invent new tools, adapted to today’s challenges. The ideal tool would be a progressive global tax on capital, coupled with a very high level of international financial transparency. Such a tax would provide a way to avoid an endless inegalitarian spiral and to control the worrisome dynamics of global capital concentration. Whatever tools and regulations are actually decided on need to be measured against this ideal. I will begin by analyzing practical aspects of such a tax and then proceed to more general reflections about the regula- tion of capitalism from the prohibition of usury to Chinese capital controls.

---

### A Global Tax on Capital: A Useful Utopia

A global tax on capital is a utopian idea. It is hard to imagine the nations of the world agreeing on any such thing anytime soon. To achieve this goal, they would have to establish a tax schedule applicable to all wealth around the world and then decide how to apportion the revenues. But if the idea is uto- pian, it is nevertheless useful, for several reasons. First, even if nothing resem- bling this ideal is put into practice in the foreseeable future, it can serve as a worthwhile reference point, a standard against which alternative proposals can be measured. Admittedly, a global tax on capital would require a very high and no doubt unrealistic level of international cooperation. But countries wishing to move in this direction could very well do so incrementally, starting at the regional level (in Europe, for instance). Unless something like this hap- pens, a defensive reaction of a nationalist stripe would very likely occur. For example, one might see a return to various forms of protectionism coupled with imposition of capital controls. Because such policies are seldom effective, however, they would very likely lead to frustration and increase international tensions. Protectionism and capital controls are actually unsatisfactory sub- stitutes for the ideal form of regulation, which is a global tax on capital—a solution that has the merit of preserving economic openness while effectively regulating the global economy and justly distributing the benefits among and within nations. Many people will reject the global tax on capital as a danger- ous illusion, just as the income tax was rejected in its time, a little more than a century ago. When looked at closely, however, this solution turns out to be far less dangerous than the alternatives.

To reject the global tax on capital out of hand would be all the more re- grettable because it is perfectly possible to move toward this ideal solution step by step, first at the continental or regional level and then by arranging for closer cooperation among regions. One can see a model for this sort of ap- proach in the recent discussions on automatic sharing of bank data between the United States and the European Union. Furthermore, various forms of capi- tal taxation already exist in most countries, especially in North America and Europe, and these could obviously serve as starting points. The capital con- trols that exist in China and other emerging countries also hold useful lessons for all. There are nevertheless important differences between these existing measures and the ideal tax on capital.

First, the proposals for automatic sharing of banking information cur- rently under discussion are far from comprehensive. Not all asset types are in- cluded, and the penalties envisioned are clearly insufficient to achieve the de- sired results (despite new US banking regulations that are more ambitious than any that exist in Europe). The debate is only beginning, and it is unlikely to produce tangible results unless relatively heavy sanctions are imposed on banks and, even more, on countries that thrive on financial opacity.

The issue of financial transparency and information sharing is closely re- lated to the ideal tax on capital. Without a clear idea of what all the information is to be used for, current data-sharing proposals are unlikely to achieve the desired result. To my mind, the objective ought to be a progressive annual tax on individual wealth—that is, on the net value of assets each person controls.

---

For the wealthiest people on the planet, the tax would thus be based on indi- vidual net worth—the kinds of numbers published by Forbes and other maga- zines. (And collecting such a tax would tell us whether the numbers published in the magazines are anywhere near correct.) For the rest of us, taxable wealth would be determined by the market value of all financial assets (including bank deposits, stocks, bonds, partnerships, and other forms of participation in listed and unlisted firms) and nonfinancial assets (especially real estate), net of debt. So much for the basis of the tax. At what rate would it be levied? One might imagine a rate of 0 percent for net assets below 1 million euros, 1 percent between 1 and 5 million, and 2 percent above 5 million. Or one might prefer a much more steeply progressive tax on the largest fortunes (for example, a rate of 5 or 10 percent on assets above 1 billion euros). There might also be advantages to having a minimal rate on modest-to-average wealth (for example, 0.1 percent below 200,000 euros and 0.5 percent between 200,000 and 1 million).
I discuss these issues later on. Here, the important point to keep in mind is that the capital tax I am proposing is a progressive annual tax on global wealth. The largest fortunes are to be taxed more heavily, and all types of assets are to be included: real estate, financial assets, and business assets—no exceptions. This is one clear difference between my proposed capital tax and the taxes on capital that currently exist in one country or another, even though important aspects of those existing taxes should be retained. To begin with, nearly every country taxes real estate: the English-speaking countries have “property taxes,” while France has a taxe foncière. One drawback of these taxes is that they are based solely on real property. (Financial assets are ignored, and property is taxed at its market value regardless of debt, so that a heavily indebted person is taxed in the same way as a person with no debt.) Furthermore, real estate is gen- erally taxed at a flat rate, or close to it. Still, such taxes exist and generate signifi- cant revenue in most developed countries, especially in the English-speaking world (typically 1–2 percent of national income). Furthermore, property taxes in some countries (such as the United States) rely on fairly sophisticated assess- ment procedures with automatic adjustment to changing market values, proce- dures that ought to be generalized and extended to other asset classes. In some European countries (including France, Switzerland, Spain, and until recently Germany and Sweden), there are also progressive taxes on total wealth. Super- ficially, these taxes are closer in spirit to the ideal capital tax I am proposing. In practice, however, they are often riddled with exemptions. Many asset classes are left out, while others are assessed at arbitrary values having nothing to do with their market value. That is why several countries have moved to eliminate such taxes. it is important to heed the lessons of these various experi- ences in order to design an appropriate capital tax for the century ahead.

---


### Democratic and Financial Transparency
What tax schedule is ideal for my proposed capital tax, and what revenues should we expect such a tax to produce? Before I attempt to answer these ques- tions, note that the proposed tax is in no way intended to replace all existing taxes. It would never be more than a fairly modest supplement to the other revenue streams on which the modern social state depends: a few points of national income (three or four at most—still nothing to sneeze at).1 The pri- mary purpose of the capital tax is not to finance the social state but to regu- late capitalism. The goal is first to stop the indefinite increase of inequality of wealth, and second to impose effective regulation on the financial and bank- ing system in order to avoid crises. To achieve these two ends, the capital tax must first promote democratic and financial transparency: there should be clarity about who owns what assets around the world.

Why is the goal of transparency so important? Imagine a very low global tax on capital, say a flat rate of 0.1 percent a year on all assets. The revenue from such a tax would of course be limited, by design: if the global stock of private capital is about five years of global income, the tax would generate revenue equal to 0.5 percent of global income, with minor variations from country to country according to their capital/income ratio (assuming that the tax is col- lected in the country where the owner of the asset resides and not where the asset itself is located—an assumption that can by no means be taken for granted). Even so, such a limited tax would already play a very useful role.
First, it would generate information about the distribution of wealth. Na- tional governments, international organizations, and statistical offices around the world would at last be able to produce reliable data about the evolution of global wealth. Citizens would no longer be forced to rely on Forbes, glossy fi- nancial reports from global wealth managers, and other unofficial sources to fill the official statistical void. (Recall that I explored the deficiencies of those unofficial sources in Part Three.) Instead, they would have access to public data based on clearly prescribed methods and information provided under penalty of law. The benefit to democracy would be considerable: it is very dif- ficult to have a rational debate about the great challenges facing the world today—the future of the social state, the cost of the transition to new sources of energy, state-building in the developing world, and so on—because the global distribution of wealth remains so opaque. Some people think that the world’s billionaires have so much money that it would be enough to tax them at a low rate to solve all the world’s problems. Others believe that there are so few billionaires that nothing much would come of taxing them more heavily. As we saw in Part Three, the truth lies somewhere between these two ex- tremes. In macroeconomic terms, one probably has to descend a bit in the wealth hierarchy (to fortunes of 10–100 million euros rather than 1 billion) to obtain a tax basis large enough to make a difference. I have also discovered some objectively disturbing trends: without a global tax on capital or some similar policy, there is a substantial risk that the top centile’s share of global wealth will continue to grow indefinitely—and this should worry everyone. In any case, truly democratic debate cannot proceed without reliable statistics.

The stakes for financial regulation are also considerable. The international organizations currently responsible for overseeing and regulating the global financial system, starting with the IMF, have only a very rough idea of the global distribution of financial assets, and in particular of the amount of as- sets hidden in tax havens. As I have shown, the planet’s financial accounts are not in balance. (Earth seems to be perpetually indebted to Mars.) Navigating our way through a global financial crisis blanketed in such a thick statistical fog is fraught with peril. Take, for example, the Cypriot banking crisis of 2013. Neither the European authorities nor the IMF had much information about who exactly owned the financial assets deposited in Cyprus or what amounts they owned, hence their proposed solutions proved crude and ineffec- tive. As we will see in the next chapter, greater financial transparency would not only lay the groundwork for a permanent annual tax on capital; it would also pave the way to a more just and efficient management of banking crises like the one in Cyprus, possibly by way of carefully calibrated and progressive special levies on capital.

---

An 0.1 percent tax on capital would be more in the nature of a compulsory reporting law than a true tax. Everyone would be required to report own- ership of capital assets to the world’s financial authorities in order to be recog- nized as the legal owner, with all the advantages and disadvantages thereof.
As noted, this was what the French Revolution accomplished with its com- pulsory reporting and cadastral surveys. The capital tax would be a sort of cadastral financial survey of the entire world, and nothing like it currently exists.2 It is important to understand that a tax is always more than just a tax: it is also a way of defining norms and categories and imposing a legal frame- work on economic activity. This has always been the case, especially in regard to land ownership.3 In the modern era, the imposition of new taxes around the time of World War I required precise definitions of income, wages, and profits. This fiscal innovation in turn fostered the development of accounting standards, which had not previously existed. One of the main goals of a tax on capital would thus be to refine the definitions of various asset types and set rules for valuing assets, liabilities, and net wealth. Under the private account- ing standards now in force, prescribed procedures are imperfect and often vague. These flaws have contributed to the many financial scandals the world has seen since 2000.

Last but not least, a capital tax would force governments to clarify and broaden international agreements concerning the automatic sharing of bank- ing data. The principle is quite simple: national tax authorities should receive all the information they need to calculate the net wealth of every citizen. In- deed, the capital tax should work in the same way as the income tax currently does in many countries, where data on income are provided to the tax au- thorities by employers (via the W-2 and 1099 forms in the United States, for example). There should be similar reporting on capital assets (indeed, income and capital reporting could be combined into one form). All taxpayers would receive a form listing their assets and liabilities as reported to the tax authori- ties. Many US states use this method to administer the property tax: taxpay- ers receive an annual form indicating the current market value of any real es- tate they own, as calculated by the government on the basis of observed prices in transactions involving comparable properties. Taxpayers can of course challenge these valuations with appropriate evidence. In practice, corrections are rare, because data on real estate transactions are readily available and hard to contest: nearly everyone is aware of changing real estate values in the local market, and the authorities have comprehensive databases at their disposal.5 Note, in passing, that this reporting method has two advantages: it makes the taxpayer’s life simple and eliminates the inevitable temptation to slightly un- derestimate the value of one’s own property.

It is essential—and perfectly feasible—to extend this reporting system to all types of financial assets (and debts). For assets and liabilities associated with financial institutions within national borders, this could be done imme- diately, since banks, insurance companies, and other financial intermediaries in most developed countries are already required to inform the tax authori- ties about bank accounts and other assets they administer. In France, for ex- ample, the government knows that Monsieur X owns an apartment worth 400,000 euros and a stock portfolio worth 200,000 euros and has 100,000 euros in outstanding debts. It could thus send him a form indicating these various amounts (along with his net worth of 500,000 euros) with a request for corrections and additions if appropriate. This type of automated system, applied to the entire population, is far better adapted to the twenty-first cen- tury than the archaic method of asking all persons to declare honestly how much they own.

---

### A Simple Solution: Automatic Transmission of Banking Information

The first step toward a global tax on capital should be to extend to the inter- national level this type of automatic transmission of banking data in order to include information on assets held in foreign banks in the precomputed asset statements issued to each taxpayer. It is important to recognize that there is no technical obstacle to doing so. Banking data are already automatically shared with the tax authorities in a country with 300 million people like the United States, as well as in countries like France and Germany with popula- tions of 60 and 80 million, respectively, so there is obviously no reason why including the banks in the Cayman Islands and Switzerland would radically increase the volume of data to be processed. Of course the tax havens regu- larly invoke other excuses for maintaining bank secrecy. One of these is the alleged worry that governments will misuse the information. This is not a very convincing argument: it is hard to see why it would not also apply to in- formation about the bank accounts of those incautious enough to keep their money in the country where they pay taxes. The most plausible reason why tax havens defend bank secrecy is that it allows their clients to evade their fiscal obligations, thereby allowing the tax havens to share in the gains. Obviously this has nothing whatsoever to do with the principles of the market economy.

---

No one has the right to set his own tax rates. It is not right for individuals to grow wealthy from free trade and economic integration only to rake off the profits at the expense of their neighbors. That is outright theft.
To date, the most thoroughgoing attempt to end these practices is the Foreign Account Tax Compliance Act (FATCA) adopted in the United States in 2010 and scheduled to be phased in by stages in 2014 and 2015. It requires all foreign banks to inform the Treasury Department about bank accounts and investments held abroad by US taxpayers, along with any other sources of reve- nue from which they might benefit. This is a far more ambitious law than the 2003 EU directive on foreign savings, which concerns only interest-bearing de- posit accounts (equity portfolios are not covered, which is unfortunate, since large fortunes are held primarily in the form of stocks, which are fully covered by FATCA) and applies only to European banks and not worldwide (again un- like FATCA). Even though the European directive is timid and almost mean- ingless, it is not enforced, since, despite numerous discussions and proposed amendments since 2008, Luxembourg and Austria managed to win from other EU member states an agreement to extend their exemption from automatic data reporting and retain their right to share information only on formal re- quest. This system, which also applies to Switzerland and other territories out- side the European Union,8 means that a government must already possess something close to proof of fraud in order to obtain information about the foreign bank accounts of one of its citizens. This obviously limits drastically the ability to detect and control fraud. In 2013, after Luxembourg and Switzerland announced their intention to abide by the provisions of FATCA, discussions in Europe resumed with the intention of incorporating some or all of these in a new EU directive. It is impossible to know when these discussions will con- clude or whether they will lead to a legally binding agreement.

Note, moreover, that in this realm there is often a chasm between the tri- umphant declarations of political leaders and the reality of what they accom- plish. This is extremely worrisome for the future equilibrium of our democratic societies. It is particularly striking to discover that the countries that are most dependent on substantial tax revenues to pay for their social programs, namely the European countries, are also the ones that have accomplished the least, even though the technical challenges are quite simple. This is a good example of the difficult situation that smaller countries face in dealing with globaliza- tion. Nation-states built over centuries find that they are too small to impose and enforce rules on today’s globalized patrimonial capitalism. The countries of Europe were able to unite around a single currency (to be discussed more extensively in the next chapter), but they have accomplished almost nothing in the area of taxation. The leaders of the largest countries in the European Union, who naturally bear primary responsibility for this failure and for the gaping chasm between their words and their actions, nevertheless continue to blame other countries and the institutions of the European Union itself. There is no reason to think that things will change anytime soon.

Furthermore, although FATCA is far more ambitious than any EU direc- tive in this realm, it, too, is insufficient. For one thing, its language is not suf- ficiently precise or comprehensive, so that there is good reason to believe that certain trust funds and foundations can legally avoid any obligation to report their assets. For another, the sanction envisioned by the law (a 30 percent sur- tax on income that noncompliant banks derive from their US operations) is insufficient. It may be enough to persuade certain banks (such as the big Swiss and Luxembourgian institutions that need to do business in the United States) to abide by the law, but there may well be a resurgence of smaller banks that specialize in managing overseas portfolios and do not operate on US soil. Such institutions, whether located in Switzerland, Luxembourg, London, or more exotic locales, can continue to manage the assets of US (or European) tax- payers without conveying any information to the authorities, with complete impunity.
Very likely the only way to obtain tangible results is to impose automatic sanctions not only on banks but also on countries that refuse to require their financial institutions to provide the required information. One might contem- plate, for example, a tariff of 30 percent or more on the exports of offending states. To be clear, the goal is not to impose a general embargo on tax havens or engage in an endless trade war with Switzerland or Luxembourg. Protec- tionism does not produce wealth, and free trade and economic openness are ultimately in everyone’s interest, provided that some countries do not take advantage of their neighbors by siphoning off their tax base. The requirement to provide comprehensive banking data automatically should have been part of the free trade and capital liberalization agreements negotiated since 1980. It was not, but that is not a good reason to stick with the status quo forever.

 Countries that have thrived on financial opacity may find it difficult to accept reform, especially since a legitimate financial services industry often develops alongside illicit (or questionable) banking activities. The financial services in- dustry responds to genuine needs of the real international economy and will obviously continue to exist no matter what regulations are adopted. Never- theless, the tax havens will undoubtedly suffer significant losses if financial transparency becomes the norm.9 Such countries would be unlikely to agree to reform without sanctions, especially since other countries, and in particular the largest countries in the European Union, have not for the moment shown much determination to deal with the problem. Note, moreover, that the construction of the European Union has thus far rested on the idea that each country could have a single market and free capital flows without paying any price (or much of one). Reform is necessary, even indispensable, but it would be naïve to think that it will happen without a fight. Because it moves the debate away from the realm of abstractions and high-flown rhetoric and toward concrete sanctions, which are important, especially in Europe, FATCA is useful.

Finally, note that neither FATCA nor the EU directives were intended to support a progressive tax on global wealth. Their purpose was primarily to provide the tax authorities with information about taxpayer assets to be used for internal purposes such as identifying omissions in income tax returns. The information can also be used to identify possible evasion of the estate tax or wealth tax (in countries that have one), but the primary emphasis is on en- forcement of the income tax. Clearly, these various issues are closely related, and international financial transparency is a crucial matter for the modern fiscal state across the board.

---

### What Is the Purpose of a Tax on Capital?

Suppose next that the tax authorities are fully informed about the net asset position of each citizen. Should they be content to tax wealth at a very low rate (of, say, 0.1 percent, in keeping with the logic of compulsory reporting), or should a more substantial tax be assessed, and if so, why? The key question can be reformulated as follows. Since a progressive income tax exists and, in most countries, a progressive estate tax as well, what is the purpose of a pro- gressive tax on capital? In fact, these three progressive taxes play distinct and complementary roles. Each is an essential pillar of an ideal tax system.10 There are two distinct justifications of a capital tax: a contributive justification and an incentive justification.

The contributive logic is quite simple: income is often not a well-defined concept for very wealthy individuals, and only a direct tax on capital can cor- rectly gauge the contributive capacity of the wealthy. Concretely, imagine a person with a fortune of 10 billion euros. As we saw in our examination of the Forbes rankings, fortunes of this magnitude have increased very rapidly over the past three decades, with real growth rates of 6–7 percent a year or even higher for the wealthiest individuals (such as Liliane Bettencourt and Bill Gates).11 By definition, this means that income in the economic sense, includ- ing dividends, capital gains, and all other new resources capable of financing consumption and increasing the capital stock, amounted to at least 6–7 per- cent of the individual’s capital (assuming that virtually none of this is con- sumed).12 To simplify things, imagine that the individual in question enjoys an economic income of 5 percent of her fortune of 10 billion euros, which would be 500 million a year. Now, it is unlikely that such an individual would declare an income of 500 million euros on her income tax return. In France, the United States, and all other countries we have studied, the largest incomes declared on income tax returns are generally no more than a few tens of mil- lions of euros or dollars. Take Liliane Bettencourt, the L’Oréal heiress and the wealthiest person in France. According to information published in the press and revealed by Bettencourt herself, her declared income was never more than 5 million a year, or little more than one ten-thousandth of her wealth (which is currently more than 30 billion euros). Uncertainties about individual cases aside (they are of little importance), the income declared for tax purposes in a case like this is less than a hundredth of the taxpayer’s economic income.

The crucial point here is that no tax evasion or undeclared Swiss bank ac- count is involved (as far as we know). Even a person of the most refined taste and elegance cannot easily spend 500 million euros a year on current expenses. It is generally enough to take a few million a year in dividends (or some other type of payout) while leaving the remainder of the return on one’s capital to accumulate in a family trust or other ad hoc legal entity created for the sole purpose of managing a fortune of this magnitude, just as university endow- ments are managed.

This is perfectly legal and not inherently problematic.14 Nevertheless, it does present a challenge to the tax system. If some people are taxed on the basis of declared incomes that are only 1 percent of their economic incomes, or even 10 percent, then nothing is accomplished by taxing that income at a rate of 50 percent or even 98 percent. The problem is that this is how the tax system works in practice in the developed countries. Effective tax rates (expressed as a percentage of economic income) are extremely low at the top of the wealth hierarchy, which is problematic, since it accentuates the explosive dynamic of wealth inequality, especially when larger fortunes are able to garner larger returns. In fact, the tax system ought to attenuate this dynamic, not accentu- ate it.
There are several ways to deal with this problem. One would be to tax all of a person’s income, including the part that accumulates in trusts, holding companies, and partnerships. A simpler solution is to compute the tax due on the basis of wealth rather than income. One could then assume a flat yield (of, say, 5 percent a year) to estimate the income on the capital and include that amount in the income subject to a progressive income tax. Some countries, such as the Netherlands, have tried this but have run into a number of diffi- culties having to do with the range of assets covered and the choice of a return on capital.15 Another solution is to apply a progressive tax directly to an indi- vidual’s total wealth. The important advantage of this approach is that one can vary the tax rate with the size of the fortune, since we know that in prac- tice larger fortunes earn larger returns.

In view of the finding that fortunes at the top of the wealth hierarchy are earning very high returns, this contributive argument is the most important justification of a progressive tax on capital. According to this reasoning, capi- tal is a better indicator of the contributive capacity of very wealthy individu- als than is income, which is often difficult to measure. A tax on capital is thus needed in addition to the income tax for those individuals whose taxable in- come is clearly too low in light of their wealth.

Nevertheless, another classic argument in favor of a capital tax should not be neglected. It relies on a logic of incentives. The basic idea is that a tax on capital is an incentive to seek the best possible return on one’s capital stock. Concretely, a tax of 1 or 2 percent on wealth is relatively light for an entre- preneur who manages to earn 10 percent a year on her capital. By contrast, it is quite heavy for a person who is content to park her wealth in investments returning at most 2 or 3 percent a year. According to this logic, the purpose of the tax on capital is thus to force people who use their wealth inefficiently to sell assets in order to pay their taxes, thus ensuring that those assets wind up in the hands of more dynamic investors.

There is some validity to this argument, but it should not be overstated.17 In practice, the return on capital does not depend solely on the talent and ef- fort supplied by the capitalist. For one thing, the average return varies system- atically with the size of the initial fortune. For another, individual returns are largely unpredictable and chaotic and are affected by all sorts of economic shocks. For example, there are many reasons why a firm might be losing money at any given point in time. A tax system based solely on the capital stock (and not on realized profits) would put disproportionate pressure on companies in the red, because their taxes would be as high when they were losing money as when they were earning high profits, and this could plunge them into bank- ruptcy.18 The ideal tax system is therefore a compromise between the incen- tive logic (which favors a tax on the capital stock) and an insurance logic (which favors a tax on the revenue stream stemming from capital).19 The un- predictability of the return on capital explains, moreover, why it is more effi- cient to tax heirs not once and for all, at the moment of inheritance (by way of the estate tax), but throughout their lives, via taxes based on both capital in- come and the value of the capital stock.20 In other words, all three types of tax—on inheritance, income, and capital—play useful and complementary roles (even if income is perfectly observable for all taxpayers, no matter how wealthy).

### A Blueprint for a European Wealth Tax

Taking all these factors into account, what is the ideal schedule for a tax on capital, and how much would such a tax bring in? To be clear, I am speaking here of a permanent annual tax on capital at a rate that must therefore be fairly moderate. A tax collected only once a generation, such as an inheritance tax, can be assessed at a very high rate: a third, a half, or even two-thirds, as was the case for the largest estates in Britain and the United States from 1930 to 1980.22 The same is true of exceptional one-time taxes on capital levied in unusual circumstances, such as the tax levied on capital in France in 1945 at rates as high as 25 percent, indeed 100 percent for additions to capital during the Occupation (1940–1945). Clearly, such taxes cannot be applied for very long: if the government takes a quarter of the nation’s wealth every year, there will be nothing left to tax after a few years. That is why the rates of an annual tax on capital must be much lower, on the order of a few percent. To some this may seem surprising, but it is actually quite a substantial tax, since it is levied every year on the total stock of capital. For example, the property tax rate is frequently just 0.5–1 percent of the value of real estate, or a tenth to a quarter of the rental value of the property (assuming an average rental return of 4 percent a year).23
The next point is important, and I want to insist on it: given the very high level of private wealth in Europe today, a progressive annual tax on wealth at modest rates could bring in significant revenue. Take, for example, a wealth tax of 0 percent on fortunes below 1 million euros, 1 percent between 1 and 5 million euros, and 2 percent above 5 million euros. If applied to all member states of the European Union, such a tax would affect about 2.5 percent of the popula- tion and bring in revenues equivalent to 2 percent of Europe’s GDP.24 The high return should come as no surprise: it is due simply to the fact that private wealth in Europe today is worth more than five years of GDP, and much of that wealth is concentrated in the upper centiles of the distribution.25 Although a tax on capital would not by itself bring in enough to finance the social state, the additional revenues it would generate are nevertheless significant.

In principle, each member state of the European Union could generate similar revenues by applying such a tax on its own. But without automatic sharing of bank information both inside and outside EU territory (starting with Switzerland among nonmember states) the risks of evasion would be very high. This partly explains why countries that have adopted a wealth tax (such as France, which employs a tax schedule similar to the one I am propos- ing) generally allow numerous exemptions, especially for “business assets” and, in practice, for nearly all large stakes in listed and unlisted companies. To do this is to drain much of the content from the progressive tax on capital, and that is why existing taxes have generated revenues so much smaller than the ones described above.26 An extreme example of the difficulties European countries face when they try to impose a capital tax on their own can be seen in Italy. In 2012, the Italian government, faced with one of the largest public debts in Europe and also with an exceptionally high level of private wealth (also one of the highest in Europe, along with Spain),27 decided to introduce a new tax on wealth. But for fear that financial assets would flee the country in search of refuge in Swiss, Austrian, and French banks, the rate was set at 0.8 percent on real estate and only 0.1 percent on bank deposits and other finan- cial assets (except stocks, which were totally exempt), with no progressivity.

Not only is it hard to think of an economic principle that would explain why some assets should be taxed at one-eighth the rate of others; the system also had the unfortunate consequence of imposing a regressive tax on wealth, since the largest fortunes consist mainly of financial assets and especially stocks. This design probably did little to earn social acceptance for the new tax, which became a major issue in the 2013 Italian elections; the candidate who had proposed the tax—with the compliments of European and international authorities—was roundly defeated at the polls. The crux of the problem is this: without automatic sharing of bank information among European coun- tries, which would allow the tax authorities to obtain reliable information about the net assets of all taxpayers, no matter where those assets are located, it is very difficult for a country acting on its own to impose a progressive tax on capital. This is especially unfortunate, because such a tax is a tool particularly well suited to Europe’s current economic predicament.


Suppose that bank information is automatically shared and the tax au- thorities have accurate assessments of who owns what, which may happen some day. What would then be the ideal tax schedule? As usual, there is no mathematical formula for answering this question, which is a matter for democratic deliberation. It would make sense to tax net wealth below 200,000 euros at 0.1 percent and net wealth between 200,000 and 1 million euros at 0.5 percent. This would replace the property tax, which in most countries is tantamount to a wealth tax on the propertied middle class. The new system would be both more just and more efficient, because it targets all assets (not only real estate) and relies on transparent data and market values net of mort- gage debt.28 To a large extent a tax of this sort could be readily implemented by individual countries acting alone.

Note that there is no reason why the tax rate on fortunes above 5 million euros should be limited to 2 percent. Since the real returns on the largest for- tunes in Europe and around the world are 6 to 7 percent or more, it would not be excessive to tax fortunes above 100 million or 1 billion euros at rates well above 2 percent. The simplest and fairest procedure would be to set rates on the basis of observed returns in each wealth bracket over several prior years. In that way, the degree of progressivity can be adjusted to match the evolution of returns to capital and the desired level of wealth concentration. To avoid divergence of the wealth distribution (that is, a steadily increasing share be- longing to the top centiles and thousandths), which on its face seems to be a

minimal desirable objective, it would probably be necessary to levy rates of about 5 percent on the largest fortunes. If a more ambitious goal is preferred— say, to reduce wealth inequality to more moderate levels than exist today (and which history shows are not necessary for growth)—one might envision rates of 10 percent or higher on billionaires. This is not the place to resolve the is- sue. What is certain is that it makes little sense to take the yield on public debt as a reference, as is often done in political debate.29 The largest fortunes are clearly not invested in government bonds.
Is a European wealth tax realistic? There is no technical reason why not. It is the tool best suited to meet the economic challenges of the twenty-first cen- tury, especially in Europe, where private wealth is thriving to a degree not seen since the Belle Époque. But if the countries of the Old Continent are to coop- erate more closely, European political institutions will have to change. The only strong European institution at the moment is the ECB, which is impor- tant but notoriously insufficient. I come back to this in the next chapter, when I turn to the question of the public debt crisis. Before that, it will be useful to look at the proposed tax on capital in a broader historical perspective.

---

### Capital Taxation in Historical Perspective

In all civilizations, the fact that the owners of capital claim a substantial share of national income without working and that the rate of return on capital is generally 4–5 percent a year has provoked vehement, often indignant, reac- tions as well as a variety of political responses. One of the most common of the latter has been the prohibition of usury, which we find in one form or an- other in most religious traditions, including those of Christianity and Islam. The Greek philosophers were of two minds about interest, which, since time never ceases to flow, can in principle increase wealth without limit. It was the danger of limitless wealth that Aristotle singled out when he observed that the word “interest” in Greek (tocos) means “child.” In his view, money ought not to “give birth” to more money.30 In a world of low or even near-zero growth, where both population and output remained more or less the same generation after generation, “limitlessness” seemed particularly dangerous.

Unfortunately, the attempts to prohibit interest were often illogical. The effect of outlawing loans at interest was generally to restrict certain types of investment and certain categories of commercial or financial activity that the political or religious authorities deemed less legitimate or worthy than others. They did not, however, question the legitimacy of returns to capital in gen- eral. In the agrarian societies of Europe, the Christian authorities never ques- tioned the legitimacy of land rents, from which they themselves benefited, as did the social groups on which they depended to maintain the social order. The prohibition of usury in the society of that time is best thought of as a form of social control: some types of capital were more difficult to control than others and therefore more worrisome. The general principle according to which capital can provide income for its owner, who need not work to justify it, went unquestioned. The idea was rather to be wary of infinite accumula- tion. Income from capital was supposed to be used in healthy ways, to pay for good works, for example, and certainly not to launch into commercial or fi- nancial adventures that might lead to estrangement from the true faith. Landed capital was in this respect very reassuring, since it could do nothing but reproduce itself year after year and century after century.31 Consequently, the whole social and spiritual order also seemed immutable. Land rent, before it became the sworn enemy of democracy, was long seen as the wellspring of social harmony, at least by those to whom it accrued.

The solution to the problem of capital suggested by Karl Marx and many other socialist writers in the nineteenth century and put into practice in the Soviet Union and elsewhere in the twentieth century was far more radical and, if nothing else, more logically consistent. By abolishing private own- ership of the means of production, including land and buildings as well as in- dustrial, financial, and business capital (other than a few individual plots of land and small cooperatives), the Soviet experiment simultaneously elimi- nated all private returns on capital. The prohibition of usury thus became general: the rate of exploitation, which for Marx represented the share of output appropriated by the capitalist, thus fell to zero, and with it the rate of private return. With zero return on capital, man (or the worker) finally threw off his chains along with the yoke of accumulated wealth. The present reas- serted its rights over the past. The inequality r>g was nothing but a bad memory, especially since communism vaunted its affection for growth and technological progress. Unfortunately for the people caught up in these to- talitarian experiments, the problem was that private property and the market economy do not serve solely to ensure the domination of capital over those who have nothing to sell but their labor power. They also play a useful role in coordinating the actions of millions of individuals, and it is not so easy to do without them. The human disasters caused by Soviet-style centralized plan- ning illustrate this quite clearly.

A tax on capital would be a less violent and more efficient response to the eternal problem of private capital and its return. A progressive levy on indi- vidual wealth would reassert control over capitalism in the name of the gen- eral interest while relying on the forces of private property and competition. Each type of capital would be taxed in the same way, with no discrimination a priori, in keeping with the principle that investors are generally in a better position than the government to decide what to invest in.32 If necessary, the tax can be quite steeply progressive on very large fortunes, but this is a matter for democratic debate under a government of laws. A capital tax is the most appropriate response to the inequality r > g as well as to the inequality of re- turns to capital as a function of the size of the initial stake.33
In this form, the tax on capital is a new idea, designed explicitly for the globalized patrimonial capitalism of the twenty-first century. To be sure, cap- ital in the form of land has been taxed since time immemorial. But property is generally taxed at a low flat rate. The main purpose of the property tax is to guarantee property rights by requiring registration of titles; it is certainly not to redistribute wealth. The English, American, and French revolutions all conformed to this logic: the tax systems they put in place were in no way in- tended to reduce inequalities of wealth. During the French Revolution the idea of progressive taxation was the subject of lively debate, but in the end the prin- ciple of progressivity was rejected. What is more, the boldest tax proposals of that time seem quite moderate today in the sense that the proposed tax rates were quite low.

The progressive tax revolution had to await the twentieth century and the period between the two world wars. It occurred in the midst of chaos and came primarily in the form of progressive taxes on income and inheritances. To be sure, some countries (most notably Germany and Sweden) established an annual progressive tax on capital as early as the late nineteenth century or early twentieth. But the United States, Britain, and France (until the 1980s) did not move in this direction.35 Furthermore, in the countries that did tax capital, the rates were relatively low, no doubt because these taxes were de- signed in a context very different from that which exists today. These taxes also suffered from a fundamental technical flaw: they were based not on the market value of the assets subject to taxation, to be revised annually, but on infrequently revised assessments of their value by the tax authorities. These assessed valuations eventually lost all connection with market values, which quickly rendered the taxes useless. The same flaw undermined the property tax in France and many other countries subsequent to the inflationary shock of the period 1914–1945.36 Such a design flaw can be fatal to a progressive tax on capital: the threshold for each tax bracket depends on more or less arbitrary factors such as the date of the last property assessment in a given town or neigh- borhood. Challenges to such arbitrary taxation became increasingly common after 1960, in a period of rapidly rising real estate and stock prices. Often the courts became involved (to rule on violations of the principle of equal taxa- tion). Germany and Sweden abolished their annual taxes on capital in 1990– 2010. This had more to do with the archaic design of these taxes (which went back to the nineteenth century) than with any response to tax competition.

The current wealth tax in France (the impôt de solidarité sur la fortune, or ISF) is in some ways more modern: it is based on the market value of various types of assets, reevaluated annually. This is because the tax was created rela- tively recently: it was introduced in the 1980s, at a time when inflation, espe- cially in asset prices, could not be ignored. There are perhaps advantages to being at odds with the rest of the developed world in regard to economic pol- icy: in some cases it allows a country to be ahead of its time.38 Although the French ISF is based on market values, in which respect it resembles the ideal capital tax, it is nevertheless quite different from the ideal in other respects. As noted earlier, it is riddled with exemptions and based on self-declared asset holdings. In 2012, Italy introduced a rather strange wealth tax, which illus- trates the limits of what a single country can do on its own in the current cli- mate. The Spanish case is also interesting. The Spanish wealth tax, like the now defunct Swedish and German ones, is based on more or less arbitrary assess- ments of real estate and other assets. Collection of the tax was suspended in 2008–2010, then restored in 2011–2012 in the midst of an acute budget crisis, but without modifications to its structure.39 Similar tensions exist almost every- where: although a capital tax seems logical in view of growing government needs (as large private fortunes increase and incomes stagnate, a govern- ment would have to be blind to pass up such a tempting source of revenue, no matter what party is in power), it is difficult to design such a tax properly within a single country.

To sum up: the capital tax is a new idea, which needs to be adapted to the globalized patrimonial capitalism of the twenty-first century. The designers of the tax must consider what tax schedule is appropriate, how the value of taxable assets should be assessed, and how information about asset ownership should be supplied automatically by banks and shared internationally so that the tax authorities need not rely on taxpayers to declare their own asset holdings.

---

### Alternative Forms of Regulation: Protectionism and Capital Controls

Is there no alternative to the capital tax? No: there are other ways to regulate patrimonial capitalism in the twenty-first century, and some of these are al- ready being tried in various parts of the world. Nevertheless, these alternative forms of regulation are less satisfactory than the capital tax and sometimes create more problems than they solve. As noted, the simplest way for a gov- ernment to reclaim a measure of economic and financial sovereignty is to re- sort to protectionism and controls on capital. Protectionism is at times a use- ful way of sheltering relatively undeveloped sectors of a country’s economy (until domestic firms are ready to face international competition).40 It is also a valuable weapon against countries that do not respect the rules (of financial transparency, health norms, human rights, etc.), and it would be foolish for a country to rule out its potential use. Nevertheless, protectionism, when de- ployed on a large scale over a long period of time, is not in itself a source of prosperity or a creator of wealth. Historical experience suggests that a coun- try that chooses this road while promising its people a robust improvement in their standard of living is likely to meet with serious disappointment. Fur- thermore, protectionism does nothing to counter the inequality r > g or the tendency for wealth to accumulate in fewer and fewer hands.

The question of capital controls is another matter. Since the 1980s, govern- ments in most wealthy countries have advocated complete and absolute liber- alization of capital flows, with no controls and no sharing of information about asset ownership among nations. International organizations such as the OECD, the World Bank, and the IMF promoted the same set of measures in the name of the latest in economic science.41 But the movement was propelled essentially by democratically elected governments, reflecting the dominant ideas of a particular historical moment marked by the fall of the Soviet Union and unlimited faith in capitalism and self-regulating markets. Since the fi- nancial crisis of 2008, serious doubts about the wisdom of this approach have arisen, and it is quite likely that the rich countries will have increasing recourse to capital controls in the decades ahead. The emerging world has shown the way, starting in the aftermath of the Asian financial crisis of 1998, which con- vinced many countries, including Indonesia, Brazil, and Russia, that the poli- cies and “shock therapies” dictated by the international community were not always well advised and the time had come to set their own courses. The crisis also encouraged some countries to amass excessive reserves of foreign exchange. This may not be the optimal response to global economic instability, but it has the virtue of allowing single countries to cope with economic shocks without forfeiting their sovereignty.

---

### The Mystery of Chinese Capital Regulation

It is important to recognize that some countries have always enforced capital controls and remained untouched by the stampede toward complete deregu- lation of financial flows and current accounts. A notable example of such a country is China, whose currency has never been convertible (though it may be someday, when China is convinced that it has accumulated sufficient re- serves to bury any speculator who bets against the renminbi). China has also imposed strict controls on both incoming capital (no one can invest in or purchase a large Chinese firm without authorization from the government, which is generally granted only if the foreign investor is content to take a mi- nority stake) and outgoing capital (no assets can be removed from China without government approval). The issue of outgoing capital is currently quite a sensitive one in China and is at the heart of the Chinese model of capital regulation. This raises a very simple question: Are China’s millionaires and billionaires, whose names are increasingly prevalent in global wealth rankings, truly the owners of their wealth? Can they, for example, take their money out of China if they wish? Although the answers to these questions are shrouded in mystery, there is no doubt that the Chinese notion of property rights is dif- ferent from the European or American notions. It depends on a complex and evolving set of rights and duties. To take one example, a Chinese billionaire who acquired a 20 percent stake in Telecom China and who wished to move to Switzerland with his family while holding on to his shares and collecting millions of euros in dividends would very likely have a much harder time do- ing so than, say, a Russian oligarch, to judge by the fact that vast sums com- monly leave Russia for suspect destinations. One never sees this in China, at least for now. In Russia, to be sure, an oligarch must take care not to tangle with the president, which can land him in prison. But if he can avoid such trouble, he can apparently live quite well on wealth derived from exploitation of Russia’s natural resources. In China things seem to be controlled more tightly. That is one of many reasons why the kinds of comparisons that one reads frequently in the Western press between the fortunes of wealthy Chi- nese political leaders and their US counterparts, who are said to be far less wealthy, probably cannot withstand close scrutiny.42
It is not my intention to defend China’s system of capital regulation, which is extremely opaque and probably unstable. Nevertheless, capital con- trols are one way of regulating and containing the dynamics of wealth ine- quality. Furthermore, China has a more progressive income tax than Russia (which adopted a flat tax in the 1990s, like most countries in the former So- viet bloc), though it is still not progressive enough. The revenues it brings in are invested in education, health, and infrastructure on a far larger scale than in other emerging countries such as India, which China has clearly outdis- tanced.43 If China wishes, and above all if its elites agree to allow the kind of democratic transparency and government of laws that go hand in hand with a modern tax system (by no means a certainty), then China is clearly large enough to impose the kind of progressive tax on income and capital that I have been discussing. In some respects, it is better equipped to meet these challenges than Europe is, because Europe must contend with political frag- mentation and with a particularly intense form of tax competition, which may be with us for some time to come.

In any case, if the European countries do not join together to regulate capital cooperatively and effectively, individual countries are highly likely to impose their own controls and national preferences. (Indeed, this has already begun, with a sometimes irrational promotion of national champions and domestic stockholders, on the frequently illusory premise that they can be more easily controlled than foreign stockholders.) In this respect, China has a clear advantage and will be difficult to beat. The capital tax is the liberal form of capital control and is better suited to Europe’s comparative advantage.

The Redistribution of Petroleum Rents
When it comes to regulating global capitalism and the inequalities it gener- ates, the geographic distribution of natural resources and especially of “petro- leum rents” constitutes a special problem. International inequalities of wealth—and national destinies—are determined by the way borders were drawn, in many cases quite arbitrarily. If the world were a single global demo- cratic community, an ideal capital tax would redistribute petroleum rents in an equitable manner. National laws sometimes do this by declaring natural resources to be common property. Such laws of course vary from country to country. It is to be hoped that democratic deliberation will point in the right direction. For example, if, tomorrow, someone were to find in her backyard a treasure greater than all of her country’s existing wealth combined, it is likely that a way would be found to amend the law to share that wealth in a reason- able manner (or so one hopes).

Since the world is not a single democratic community, however, the redis- tribution of natural resources is often decided in far less peaceful ways. In 1990–1991, just after the collapse of the Soviet Union, another fateful event took place. Iraq, a country of 35 million people, decided to invade its tiny neighbor, Kuwait, with barely 1 million people but in possession of petroleum reserves virtually equal to those of Iraq. This was in part a geographical acci- dent, of course, but it was also the result of a stroke of the postcolonial pen: Western oil companies and their governments in some cases found it easier to do business with countries without too many people living in them (although the long-term wisdom of such a choice may be doubted). In any case, the West- ern powers and their allies immediately sent some 900,000 troops to restore the Kuwaitis as the sole legitimate owners of their oilfields (proof, if proof were needed, that governments can mobilize impressive resources to enforce their decisions when they choose to do so). This happened in 1991. The first Gulf war was followed by a second in 2003, in Iraq, with a somewhat sparser coalition of Western powers. The consequences of these events are still with us today.
It is not up to me to calculate the optimal schedule for the tax on petro- leum capital that would ideally exist in a global political community based on social justice and utility, or even in a Middle Eastern political community. I observe simply that the unequal distribution of wealth in this region has at- tained unprecedented levels of injustice, which would surely have ceased to exist long ago were it not for foreign military protection. In 2012, the total budget of the Egyptian ministry of education for all primary, middle, and secondary schools and universities in a country of 85 million was less than $5 billion.45 A few hundred kilometers to the east, Saudi Arabia and its 20 mil- lion citizens enjoyed oil revenues of $300 billion, while Qatar and its 300,000 Qataris take in more than $100 billion annually. Meanwhile, the interna- tional community wonders if it ought to extend a loan of a few billion dollars to Egypt or wait until the country increases, as promised, its tax on carbon- ated drinks and cigarettes. Surely the international norm should be to prevent redistribution of wealth by force of arms insofar as it is possible to do so (par- ticularly when the intention of the invader is to buy more arms, not to build schools, as was the case with the Iraqi invader in 1991). But such a norm should carry with it the obligation to find other ways to achieve a more just distribu- tion of petroleum rents, be it by way of sanctions, taxes, or foreign aid, in order to give countries without oil the opportunity to develop.

---

### Redistribution through Immigration

A seemingly more peaceful form of redistribution and regulation of global wealth inequality is immigration. Rather than move capital, which poses all sorts of difficulties, it is sometimes simpler to allow labor to move to places where wages are higher. This was of course the great contribution of the United States to global redistribution: the country grew from a population of barely 3 million at the time of the Revolutionary War to more than 300 mil- lion today, largely thanks to successive waves of immigration. That is why the United States is still a long way from becoming the new Old Europe, as I speculated it might in Chapter 14. Immigration is the mortar that holds the United States together, the stabilizing force that prevents accumulated capital from acquiring the importance it has in Europe; it is also the force that makes the increasingly large inequalities of labor income in the United States politi- cally and socially bearable. For a fair proportion of Americans in the bottom 50 percent of the income distribution, these inequalities are of secondary im- portance for the very simple reason that they were born in a less wealthy country and see themselves as being on an upward trajectory. Note, moreover, that the mechanism of redistribution through immigration, which enables individuals born in poor countries to improve their lot by moving to a rich

country, has lately been an important factor in Europe as well as the United States. In this respect, the distinction between the Old World and the New may be less salient than in the past.46
It bears emphasizing, however, that redistribution through immigration, as desirable as it may be, resolves only part of the problem of inequality. Even after average per capita output and income are equalized between countries by way of immigration and, even more, by poor countries catching up with rich ones in terms of productivity, the problem of inequality—and in particu- lar the dynamics of global wealth concentration—remains. Redistribution through immigration postpones the problem but does not dispense with the need for a new type of regulation: a social state with progressive taxes on in- come and capital. One might hope, moreover, that immigration will be more readily accepted by the less advantaged members of the wealthier societies if such institutions are in place to ensure that the economic benefits of global- ization are shared by everyone. If you have free trade and free circulation of capital and people but destroy the social state and all forms of progressive taxation, the temptations of defensive nationalism and identity politics will very likely grow stronger than ever in both Europe and the United States.
Note, finally, that the less developed countries will be among the primary beneficiaries of a more just and transparent international tax system. In Af- rica, the outflow of capital has always exceeded the inflow of foreign aid by a wide margin. It is no doubt a good thing that several wealthy countries have launched judicial proceedings against former African leaders who fled their countries with ill-gotten gains. But it would be even more useful to establish international fiscal cooperation and data sharing to enable countries in Africa and elsewhere to root out such pillage in a more systematic and methodical fashion, especially since foreign companies and stockholders of all nationali- ties are at least as guilty as unscrupulous African elites. Once again, financial transparency and a progressive global tax on capital are the right answers.

