---
title       : Chapter 16 -- The Question of the Public Debt
subtitle    : Thomas Piketty, Capital in the 21st Century (Harvard University Press 2014)
author      : Patrick Toche
framework   : io2012  # minimal, io2012, html5slides, shower, dzslides
mode        : selfcontained  # selfcontained, standalone, draft
widgets     : mathjax   # [mathjax, quiz, bootstrap]
ext_widgets : {rCharts: [libraries/nvd3]}  # libraries/morris, libraries/highcharts, libraries/rickshaw, libraries/dimple
url         : {lib: "../../libraries", assets: "../../assets"}
lecnum      : "16"
--- {class: cover-slide}

```{r 'preamble', message = FALSE, warning = FALSE, error = FALSE, echo = FALSE, tidy = FALSE, comment = NA, cache = FALSE}
require(knitr)
library(png)   # to display external png and control dimensions
library(grid)  # to display external png and control dimensions
opts_chunk$set(echo = FALSE, cache = FALSE)
source('../../shared/shared.R')
```

---

### Introduction  

- This set of slides surveys selected topics from *Capital in the Twenty-First Century*, a book written by economist Thomas Piketty, published in English in 2014 to great acclaim.
- All source files for this course are available for download by anyone without restrictions at https://github.com/ptoche/piketty
- The full course is expected to be completed by April 2015.
- Chapter 15 considered a global tax on capital.
- Chapter 16 examines the question of the public debt.

---

The Question of the Public Debt
There are two main ways for a government to finance its expenses: taxes and debt. In general, taxation is by far preferable to debt in terms of justice and efficiency. The problem with debt is that it usually has to be repaid, so that debt financing is in the interest of those who have the means to lend to the government. From the standpoint of the general interest, it is normally prefer- able to tax the wealthy rather than borrow from them. There are nevertheless many reasons, both good and bad, why governments sometimes resort to bor- rowing and to accumulating debt (if they do not inherit it from previous governments). At the moment, the rich countries of the world are enmeshed in a seemingly interminable debt crisis. To be sure, history offers examples of even higher public debt levels, as we saw in Part Two: in Britain in particular, public debt twice exceeded two years of national income, first at the end of the Napoleonic wars and again after World War II. Still, with public debt in the rich countries now averaging about one year of national income (or 90 percent of GDP), the developed world is currently indebted at a level not seen since 1945. Although the emerging economies are poorer than the rich ones in both income and capital, their public debt is much lower (around 30 percent of GDP on average). This shows that the question of public debt is a question of the distribution of wealth, between public and private actors in particular, and not a question of absolute wealth. The rich world is rich, but the govern- ments of the rich world are poor. Europe is the most extreme case: it has both the highest level of private wealth in the world and the greatest difficulty in resolving its public debt crisis—a strange paradox.
I begin by examining various ways of dealing with high public debt levels. This will lead to an analysis of how central banks regulate and redistribute capital and why European unification, overly focused as it was on the issue of currency while neglecting taxation and debt, has led to an impasse. Finally, I will explore the optimal accumulation of public capital and its relation to private capital in the probable twenty-first-century context of low growth and potential degradation of natural capital.
Reducing Public Debt: Tax on Capital, Inflation, and Austerity
How can a public debt as large as today’s European debt be significantly re- duced? There are three main methods, which can be combined in various pro- portions: taxes on capital, inflation, and austerity. An exceptional tax on pri- vate capital is the most just and efficient solution. Failing that, inflation can play a useful role: historically, that is how most large public debts have been dealt with. The worst solution in terms of both justice and efficiency is a pro- longed dose of austerity—yet that is the course Europe is currently following.
I begin by recalling the structure of national wealth in Europe today. As I showed in Part Two, national wealth in most European countries is close to six years of national income, and most of it is owned by private agents (house- holds). The total value of public assets is approximately equal to the total public debt (about one year of national income), so net public wealth is close to zero.1 Private wealth (net of debt) can be divided into two roughly equal halves: real estate and financial assets. Europe’s average net asset position vis- à-vis the rest of the world is close to equilibrium, which means that European firms and sovereign debt are owned by European households (or, more pre- cisely, what the rest of the world owns of Europe is compensated by what Eu- ropeans own of the rest of the world). This reality is obscured by the complex- ity of the system of financial intermediation: people deposit their savings in a bank or invest in a financial product, and the bank then invests the money elsewhere. There is also considerable cross-ownership between countries, which makes things even more opaque. Yet the fact remains that European households (or at any rate those that own anything at all: bear in mind that wealth is still very concentrated, with 60 percent of the total owned by the wealthiest 10 percent) own the equivalent of all that there is to own in Eu- rope, including its public debt.2
Under such conditions, how can public debt be reduced to zero? One solu- tion would be to privatize all public assets. According to the national ac- counts of the various European countries, the proceeds from selling all public buildings, schools, universities, hospitals, police stations, infrastructure, and so on would be roughly sufficient to pay off all outstanding public debt.3 In- stead of holding public debt via their financial investments, the wealthiest European households would become the direct owners of schools, hospitals, police stations, and so on. Everyone else would then have to pay rent to use these assets and continue to produce the associated public services. This solu- tion, which some very serious people actually advocate, should to my mind be dismissed out of hand. If the European social state is to fulfill its mission ad- equately and durably, especially in the areas of education, health, and security, it must continue to own the related public assets. It is nevertheless important to understand that as things now stand, governments must pay heavy interest (rather than rent) on their outstanding public debt, so the situation is not all that different from paying rent to use the same assets, since these interest pay- ments weigh just as heavily on the public exchequer.
A much more satisfactory way of reducing the public debt is to levy an exceptional tax on private capital. For example, a flat tax of 15 percent on pri- vate wealth would yield nearly a year’s worth of national income and thus al- low for immediate reimbursement of all outstanding public debt. The state would continue to own its public assets, but its debt would be reduced to zero after five years and it would therefore have no interest to pay.4 This solution is equivalent to a total repudiation of the public debt, except for two essential differences.5
First, it is always very difficult to predict the ultimate incidence of a debt repudiation, even a partial one—that is, it is difficult to know who will actu- ally bear the cost. Complete or partial default on the public debt is sometimes tried in situations of extreme overindebtedness, as in Greece in 2011–2012. Bondholders are forced to accept a “haircut” (as the jargon has it): the value of government bonds held by banks and other creditors is reduced by 10–20 percent or perhaps even more. The problem is that if one applies a measure of this sort on a large scale—for example, all of Europe and not just Greece (which accounts for just 2 percent of European GDP)—it is likely to trigger a banking panic and a wave of bankruptcies. Depending on which banks are holding various types of bonds, as well as on the structure of their balance sheets, the identity of their creditors, the households that have invested their savings in these various institutions, the nature of those investments, and so on, one can end up with quite different final incidences, which cannot be ac- curately predicted in advance. Furthermore, it is quite possible that the people with the largest portfolios will be able to restructure their investments in time to avoid the haircut almost entirely. People sometimes think that impos- ing a haircut is a way of penalizing those investors who have taken the largest risks. Nothing could be further from the truth: financial assets are constantly being traded, and there is no guarantee that the people who would be penal- ized in the end are the ones who ought to be. The advantage of an exceptional tax on capital, which is similar to a haircut, is precisely that it would arrange things in a more civilized manner. Everyone would be required to contribute, and, equally important, bank failures would be avoided, since it is the ultimate owners of wealth (physical individuals) who would have to pay, not financial institutions. If such a tax were to be levied, however, the tax authorities would of course need to be permanently and automatically apprised of any bank ac- counts, stocks, bonds, and other financial assets held by the citizens under their jurisdiction. Without such a financial cadaster, every policy choice would be risky.
But the main advantage of a fiscal solution is that the contribution de- manded of each individual can be adjusted to the size of his fortune. It would not make much sense to levy an exceptional tax of 15 percent on all private wealth in Europe. It would be better to apply a progressive tax designed to spare the more modest fortunes and require more of the largest ones. In some respects, this is what European banking law already does, since it generally guarantees deposits up to 100,000 euros in case of bank failure. The progres- sive capital tax is a generalization of this logic, since it allows much finer gra- dations of required levies. One can imagine a number of different brackets: full deposit guarantee up to 100,000 euros, partial guarantee between 100,000 and 500,000 euros, and so on, with as many brackets as seem useful. The pro- gressive tax would also apply to all assets (including listed and unlisted shares), not just bank deposits. This is essential if one really wants to reach the wealth- iest individuals, who rarely keep their money in checking accounts.
In any event, it would no doubt be too much to try to reduce public debt to zero in one fell swoop. To take a more realistic example, assume that we want to reduce European government debt by around 20 percent of GDP, which would bring debt levels down from the current 90 percent of GDP to 70 percent, not far from the maximum of 60 percent set by current European treaties.6 As noted in the previous chapter, a progressive tax on capital at a rate of 0 percent on fortunes up to 1 million euros, 1 percent on fortunes between 1 and 5 million euros, and 2 percent on fortunes larger than 5 million euros would bring in the equivalent of about 2 percent of European GDP. To obtain one-time receipts of 20 percent of GDP, it would therefore suffice to apply a special levy with rates 10 times as high: 0 percent up to 1 million, 10 percent between 1 and 5 million, and 20 percent above 5 million.7 It is interesting to note that the exceptional tax on capital that France applied in 1945 in order to substantially reduce its public debt had progressive rates that ranged from 0 to 25 percent.8
One could obtain the same result by applying a progressive tax with rates of 0, 1, and 2 percent for a period of ten years and earmarking the receipts for debt reduction. For example, one could set up a “redemption fund” similar to the one proposed in 2011 by a council of economists appointed by the German government. This proposal, which was intended to mutualize all Eurozone public debt above 60 percent of GDP (and especially the debt of Germany, France, Italy, and Spain) and then to reduce the fund gradually to zero, is far from perfect. In particular, it lacks the democratic governance without which the mutualization of European debt is not feasible. But it is a concrete plan that could easily be combined with an exceptional one-time or special ten-year tax on capital.9
Does Inflation Redistribute Wealth?
To recapitulate the argument thus far: I observed that an exceptional tax on capital is the best way to reduce a large public debt. This is by far the most transparent, just, and efficient method. Inflation is another possible option, however. Concretely, since a government bond is a nominal asset (that is, an asset whose price is set in advance and does not depend on inflation) rather than a real asset (whose price evolves in response to the economic situation, generally increasing at least as fast as inflation, as in the case of real estate and shares of stock), a small increase in the inflation rate is enough to significantly reduce the real value of the public debt. With an inflation rate of 5 percent a year rather than 2 percent, the real value of the public debt, expressed as a percentage of GDP, would be reduced by more than 15 percent (all other things equal)—a considerable amount.
Such a solution is extremely tempting. Historically, this is how most large public debts were reduced, particularly in Europe in the twentieth century. For example, inflation in France and Germany averaged 13 and 17 per- cent a year, respectively, from 1913 to 1950. It was inflation that allowed both countries to embark on reconstruction efforts in the 1950s with a very small burden of public debt. Germany, in particular, is by far the country that has used inflation most freely (along with outright debt repudiation) to elimi- nate public debt throughout its history.10 Apart from the ECB, which is by far the most averse to this solution, it is no accident that all the other major central banks—the US Federal Reserve, the Bank of Japan, and the Bank of England—are currently trying to raise their inflation targets more or less explicitly and are also experimenting with various so-called unconventional monetary policies. If they succeed—say, by increasing inflation from 2 to 5 percent a year (which is by no means assured)—these countries will emerge from the debt crisis much more rapidly than the countries of the Eurozone, whose economic prospects are clouded by the absence of any obvious way out, as well as by their lack of clarity concerning the long-term future of bud- getary and fiscal union in Europe.
Indeed, it is important to understand that without an exceptional tax on capital and without additional inflation, it may take several decades to get out from under a burden of public debt as large as that which currently exists in Europe. To take an extreme case: suppose that inflation is zero and GDP grows at 2 percent a year (which is by no means assured in Europe today because of the obvious contractionary effect of budgetary rigor, at least in the short term), with a budget deficit limited to 1 percent of GDP (which in practice implies a substantial primary surplus, given the interest on the debt). Then by definition it would take 20 years to reduce the debt-to-GDP ratio by twenty points.11 If growth were to fall below 2 percent in some years and debt were to rise above 1 percent, it could easily take thirty or forty years. It takes decades to accumulate capital; it can also take a very long time to reduce a debt.
The most interesting historical example of a prolonged austerity cure can be found in nineteenth-century Britain. As noted in Chapter 3, it would have taken a century of primary surpluses (of 2–3 points of GDP from 1815 to 1914) to rid the country of the enormous public debt left over from the Napoleonic wars. Over the course of this period, British taxpayers spent more on interest on the debt than on education. The choice to do so was no doubt in the inter- est of government bondholders but unlikely to have been in the general inter- est of the British people. It may be that the setback to British education was responsible for the country’s decline in the decades that followed. To be sure, the debt was then above 200 percent of GDP (and not barely 100 percent, as is the case today), and inflation in the nineteenth century was close to zero (whereas an inflation target of 2 percent is generally accepted nowadays). Hence there is hope that European austerity might last only ten or twenty years (at a minimum) rather than a century. Still, that would be quite a long time. It is reasonable to think that Europe might find better ways to prepare for the economic challenges of the twenty-first century than to spend several points of GDP a year servicing its debt, at a time when most European coun- tries spend less than one point of GDP a year on their universities.12
That said, I want to insist on the fact that inflation is at best a very imper- fect substitute for a progressive tax on capital and can have some undesirable secondary effects. The first problem is that inflation is hard to control: once it gets started, there is no guarantee that it can be stopped at 5 percent a year. In an inflationary spiral, everyone wants to make sure that the wages he receives and the prices he must pay evolve in a way that suits him. Such a spiral can be hard to stop. In France, the inflation rate exceeded 50 percent for four con- secutive years, from 1945 to 1948. This reduced the public debt to virtually nothing in a far more radical way than the exceptional tax on capital that was collected in 1945. But millions of small savers were wiped out, and this aggra- vated the persistent problem of poverty among the elderly in the 1950s.13 In Germany, prices were multiplied by a factor of 100 million between the be- ginning of 1923 and the end. Germany’s society and economy were perma- nently traumatized by this episode, which undoubtedly continues to influ- ence German perceptions of inflation. The second difficulty with inflation is that much of the desired effect disappears once it becomes permanent and embedded in expectations (in particular, anyone willing to lend to the gov- ernment will demand a higher rate of interest).
To be sure, one argument in favor of inflation remains: compared with a capital tax, which, like any other tax, inevitably deprives people of resources they would have spent usefully (for consumption or investment), inflation (at least in its idealized form) primarily penalizes people who do not know what to do with their money, namely, those who have kept too much cash in their bank account or stuffed into their mattress. It spares those who have already spent everything or invested everything in real economic assets (real estate or business capital), and, better still, it spares those who are in debt (inflation reduces nominal debt, which enables the indebted to get back on their feet more quickly and make new investments). In this idealized version, inflation is in a way a tax on idle capital and an encouragement to dynamic capital. There is some truth to this view, and it should not be dismissed out of hand.14 But as I showed in examining unequal returns on capital as a function of the initial stake, inflation in no way prevents large and well-diversified portfolios from earning a good return simply by virtue of their size (and without any personal effort by the owner).15
In the end, the truth is that inflation is a relatively crude and imprecise tool. Sometimes it redistributes wealth in the right direction, sometimes not. To be sure, if the choice is between a little more inflation and a little more austerity, inflation is no doubt preferable. But in France one sometimes hears the view that inflation is a nearly ideal tool for redistributing wealth (a way of taking money from “German rentiers” and forcing the aging population on the other side of the Rhine to show more solidarity with the rest of Europe). This is naïve and preposterous. In practice, a great wave of inflation in Europe would have all sorts of unintended consequences for the redistribution of wealth and would be particularly harmful to people of modest means in France, Germany, and elsewhere. Conversely, those with fortunes in real es- tate and the stock market would largely be spared on both sides of the Rhine and everywhere else as well.16 When it comes to decreasing inequalities of wealth for good or reducing unusually high levels of public debt, a progressive tax on capital is generally a better tool than inflation.
What Do Central Banks Do?
In order to gain a better understanding of the role of inflation and, more gen- erally, of central banks in the regulation and redistribution of capital, it is useful to take a step back from the current crisis and to examine these issues in broader historical perspective. Back when the gold standard was the norm everywhere, before World War I, central banks played a much smaller role than they do today. In particular, their power to create money was severely limited by the existing stock of gold and silver. One obvious problem with the gold standard was that the evolution of the overall price level depended pri- marily on the hazards of gold and silver discoveries. If the global stock of gold was static but global output increased, the price level had to fall (since the same money stock now had to support a larger volume of commercial ex- change). In practice this was a source of considerable difficulty.17 If large deposits of gold or silver were suddenly discovered, as in Spanish America in the sixteenth and seventeenth centuries or California in the mid-nineteenth century, prices could skyrocket, which created other kinds of problems and brought undeserved windfalls to some.18 These drawbacks make it highly unlikely that the world will ever return to the gold standard. (Keynes referred to gold as a “barbarous relic.”)
Once currency ceases to be convertible into precious metals, however, the power of central banks to create money is potentially unlimited and must therefore be strictly regulated. This is the crux of the debate about central bank independence as well as the source of numerous misunderstandings. Let me quickly retrace the stages of this debate. At the beginning of the Great Depres- sion, the central banks of the industrialized countries adopted an extremely conservative policy: having only recently abandoned the gold standard, they refused to create the liquidity necessary to save troubled banks, which led to a wave of bankruptcies that seriously aggravated the crisis and pushed the world to the brink of the abyss. It is important to understand the trauma occasioned by this tragic historical experience. Since then, everyone agrees that the pri- mary function of central banking is to ensure the stability of the financial system, which requires central banks to assume the role of “lenders of last re- sort”: in case of absolute panic, they must create the liquidity necessary to avoid a broad collapse of the financial system. It is essential to realize that this view has been shared by all observers of the system since the 1930s, regardless of their position on the New Deal or the various forms of social state created in the United States and Europe at the end of World War II. Indeed, faith in the stabilizing role of central banking at times seems inversely proportional to faith in the social and fiscal policies that grew out of the same period.
This is particularly clear in the monumental Monetary History of the United States published in 1963 by Milton Friedman and Anna Schwartz. In this fundamental work, the leading figure in monetary economics follows in minute detail the changes in United States monetary policy from 1857 to 1960, based on voluminous archival records.19 Unsurprisingly, the focal point of the book is the Great Depression. For Friedman, no doubt is possible: it was the unduly restrictive policy of the Federal Reserve that transformed the stock market crash into a credit crisis and plunged the economy into a deflationary spiral and a depression of unprecedented magnitude. The crisis was primarily monetary, and therefore its solution was also monetary. From this analysis, Friedman drew a clear political conclusion: in order to ensure regu- lar, undisrupted growth in a capitalist economy, it is necessary and sufficient to make sure that monetary policy is designed to ensure steady growth of the money supply. Accordingly, monetarist doctrine held that the New Deal, which created a large number of government jobs and social transfer programs, was a costly and useless sham. Saving capitalism did not require a welfare state or a tentacular government: the only thing necessary was a well-run Federal Reserve. In the 1960s–1970s, although many Democrats in the United States still dreamed of completing the New Deal, the US public had begun to worry about their country’s decline relative to Europe, which was then still in a phase of rapid growth. In this political climate, Friedman’s simple but powerful political message had the effect of a bombshell. The work of Friedman and other Chicago School economists fostered suspicion of the ever-expanding state and created the intellectual climate in which the conservative revolution of 1979–1980 became possible.
One can obviously reinterpret these events in a different light: there is no reason why a properly functioning Federal Reserve cannot function as a com- plement to a properly functioning social state and a well-designed progressive tax policy. These institutions are clearly complements rather than substitutes. Contrary to monetarist doctrine, the fact that the Fed followed an unduly restrictive monetary policy in the early 1930s (as did the central banks of the other rich countries) says nothing about the virtues and limitations of other institutions. That is not the point that interests me here, however. The fact is that all economists—monetarists, Keynesians, and neoclassicals—together with all other observers, regardless of their political stripe, have agreed that central banks ought to act as lenders of last resort and do whatever is neces- sary to avoid financial collapse and a deflationary spiral.
This broad consensus explains why all of the world’s central banks—in Japan and Europe as well as the United States—reacted to the financial crisis of 2007–2008 by taking on the role of lenders of last resort and stabilizers of the financial system. Apart from the collapse of Lehman Brothers in Septem- ber 2008, bank failures in the crisis have been fairly limited in scope. There is, however, no consensus as to the exact nature of the “unconventional” mone- tary policies that should be followed in situations like this. 

What in fact do central banks do? For present purposes, it is important to realize that central banks do not create wealth as such; they redistribute it. More precisely, when the Fed or the ECB decides to create a billion additional dollars or euros, US or European capital is not augmented by that amount. In fact, national capital does not change by a single dollar or euro, because the operations in which central banks engage are always loans. They therefore re- sult in the creation of financial assets and liabilities, which, at the moment they are created, exactly balance each other. For example, the Fed might lend $1 billion to Lehman Brothers or General Motors (or the US government), and these entities contract an equivalent debt. The net wealth of the Fed and Lehman Brothers (or General Motors) does not change at all, nor, a fortiori, does that of the United States or the planet. Indeed, it would be astonishing if central banks could simply by the stroke of a pen increase the capital of their nation or the world.
What happens next depends on how this monetary policy influences the real economy. If the loan initiated by the central bank enables the recipient to escape from a bad pass and avoid a final collapse (which might decrease the national wealth), then, when the situation has been stabilized and the loan repaid, it makes sense to think that the loan from the Fed increased the na- tional wealth (or at any rate prevented national wealth from decreasing). On the other hand, if the loan from the Fed merely postpones the recipient’s in- evitable collapse and even prevents the emergence of a viable competitor (which can happen), one can argue that the Fed’s policy ultimately decreased the na- tion’s wealth. Both outcomes are possible, and every monetary policy raises both possibilities to one degree or another. To the extent that the world’s cen- tral banks limited the damage from the recession of 2008–2009, they helped to increase GDP and investment and therefore augmented the capital of the wealthy countries and of the world. Obviously, however, a dynamic evalua- tion of this kind is always uncertain and open to challenge. What is certain is that when central banks increase the money supply by lending to a financial or nonfinancial corporation or a government, there is no immediate impact on national capital (both public and private).20
What “unconventional” monetary policies have been tried since the crisis of 2007–2008? In calm periods, central banks are content to ensure that the money supply grows at the same pace as economic activity in order to guaran- tee a low inflation rate of 1 or 2 percent a year. Specifically, they create new money by lending to banks for very short periods, often no more than a few days. These loans guarantee the solvency of the entire financial system. Households and firms deposit and withdraw vast sums of money every day, and these deposits and withdrawals are never perfectly balanced for any par- ticular bank. The major innovation since 2008 has been in the duration of loans to private banks. Instead of lending for a few days, the Fed and ECB began lending for three to six months: the volume of loans of these durations increased dramatically in the last quarter of 2008 and the first quarter of 2009. They also began lending at similar durations to nonfinancial corpora- tions. In the United States especially, the Fed also made loans of nine to twelve months to the banking sector and purchased long-dated bonds outright. In 2011–2012, the central banks again expanded the range of their interventions. The Fed, the Bank of Japan, and the Bank of England had been buying sover- eign debt since the beginning of the crisis, but as the debt crisis worsened in southern Europe the ECB decided to follow suit.
These policies call for several clarifications. First, the central banks have the power to prevent a bank or nonfinancial corporation from failing by lend- ing it the money needed to pay its workers and suppliers, but they cannot oblige companies to invest or households to consume, and they cannot com- pel the economy to resume its growth. Nor do they have the power to set the rate of inflation. The liquidity created by the central banks probably warded off deflation and depression, but the economic outlook in the wealthy coun- tries remains gloomy, especially in Europe, where the crisis of the euro has un- dermined confidence. The fact that governments in the wealthiest countries (United States, Japan, Germany, France, and Britain) could borrow at excep- tionally low rates ( just over 1 percent) in 2012–2013 attests to the importance of central bank stabilization policies, but it also shows that private investors have no clear idea of what to do with the money lent by the monetary authori- ties at rates close to zero. Hence they prefer to lend their cash back to the governments deemed the most solid at ridiculously low interest rates. The fact that rates are very low in some countries and much higher in others is the sign of an abnormal economic situation.21
Central banks are powerful because they can redistribute wealth very quickly and, in theory, as extensively as they wish. If necessary, a central bank can create as many billions as it wants in seconds and credit all that cash to the account of a company or government in need. In an emergency (such as a financial panic, war, or natural disaster), this ability to create money immedi- ately in unlimited amounts is an invaluable attribute. No tax authority can move that quickly to levy a tax: it is necessary first to establish a taxable base, set rates, pass a law, collect the tax, forestall possible challenges, and so on. If this were the only way to resolve a financial crisis, all the banks in the world would already be bankrupt. Rapid execution is the principal strength of the monetary authorities.
The weakness of central banks is clearly their limited ability to decide who should receive loans in what amount and for what duration, as well as the dif- ficulty of managing the resulting financial portfolio. One consequence of this is that the size of a central bank’s balance sheet should not exceed certain limits. With all the new types of loans and financial market interventions that have been introduced since 2008, central bank balance sheets have roughly doubled in size. The sum of the Federal Reserve’s assets and liabilities has gone from 10 to more than 20 percent of GDP; the same is true of the Bank of England; and the ECB’s balance sheet has expanded from 15 to 30 percent of GDP. These are striking developments, but these sums are still fairly modest compared with total net private wealth, which is 500 to 600 percent of GDP in most of the rich countries.22
It is of course possible in the abstract to imagine much larger central bank balance sheets. The central banks could decide to buy up all of a country’s firms and real estate, finance the transition to renewable energy, invest in uni- versities, and take control of the entire economy. Clearly, the problem is that central banks are not well suited to such activities and lack the democratic legitimacy to try them. They can redistribute wealth quickly and massively, but they can also be very wrong in their choice of targets ( just as the effects of inflation on inequality can be quite perverse). Hence it is preferable to limit the size of central bank balance sheets. That is why they operate under strict mandates focused largely on maintaining the stability of the financial system. In practice, when a government decides to aid a particular branch of industry, as the United States did with General Motors in 2009–2010, it was the fed- eral government and not the Federal Reserve that took charge of making loans, acquiring shares, and setting conditions and performance objectives. The same is true in Europe: industrial and educational policy are matters for states to decide, not central banks. The problem is not one of technical impos- sibility but of democratic governance. The fact that it takes time to pass tax and spending legislation is not an accident: when significant shares of na- tional wealth are shifted about, it is best not to make mistakes.
Among the many controversies concerning limiting the role of central banks, two issues are of particular interest here. One has to do with the com- plementary nature of bank regulation and taxation of capital (as the recent crisis in Cyprus made quite clear). The other has to do with the increasingly apparent deficiencies of Europe’s current institutional architecture: the Euro- pean Union is engaged in a historically unprecedented experiment: attempt- ing to create a currency on a very large scale without a state.
The Cyprus Crisis: When the Capital Tax and Banking Regulation Come Together
The primary and indispensable role of central banking is to ensure the stabil- ity of the financial system. Central banks are uniquely equipped to evaluate the position of the various banks that make up the system and can refinance them if necessary in order to ensure that the payment system functions nor- mally. They are sometimes assisted by other authorities specifically charged with regulating the banks: for example, by issuing banking licenses and en- suring that certain financial ratios are maintained (in order to make sure that the banks keep sufficient reserves of cash and “safe” assets relative to loans and other assets deemed to be higher risk). In all countries, the central banks and bank regulators (who are often affiliated with the central banks) work to- gether. In current discussions concerning the creation of a European banking union, the ECB is supposed to play the central role. In particularly severe banking crises, central banks also work in concert with international organi- zations such as the IMF. Since 2009–2010, a “Troika” consisting of the Euro- pean Commission, the ECB, and the IMF has been working to resolve the financial crisis in Europe, which involves both a public debt crisis and a bank- ing crisis, especially in southern Europe. The recession of 2008–2009 caused a sharp rise in the public debt of many countries that were already heavily in- debted before the crisis (especially Greece and Italy) and also led to a rapid deterioration of bank balance sheets, especially in countries affected by a col- lapsing real estate bubble (most notably Spain). In the end, the two crises are inextricably linked. The banks are holding government bonds whose precise value is unknown. (Greek bonds were subjected to a substantial “haircut,”

and although the authorities have promised not to repeat this strategy else- where, the fact remains that future actions are unpredictable in such circum- stances.) State finances can only continue to get worse as long as the economic outlook continues to be bleak, as it probably will as long as the financial and credit system remains largely blocked.
One problem is that neither the Troika nor the various member state gov- ernments have automatic access to international banking data or what I have called a “financial cadaster,” which would allow them to distribute the bur- dens of adjustment in an efficient and transparent manner. I have already discussed the difficulties that Italy and Spain faced in attempting to impose a progressive tax on capital on their own in order to restore their public fi- nances to a sound footing. The Greek case is even more extreme. Everyone is insisting that Greece collect more taxes from its wealthier citizens. This is no doubt an excellent idea. The problem is that in the absence of adequate inter- national cooperation, Greece obviously has no way to levy a just and efficient tax on its own, since the wealthiest Greeks can easily move their money a broa d , o ft en to ot her Eu rop e a n cou ntr ie s . Th e Eu rope a n a nd i nter nat iona l authorities have never taken steps to implement the necessary laws and regu- lations, however.23 Lacking tax revenues, Greece has therefore been obliged to sell public assets, often at fire-sale prices, to buyers of Greek or other Euro- pean nationalities, who evidently would rather take advantage of such an opportunity than pay taxes to the Greek government.
The March 2013 crisis in Cyprus is a particularly interesting case to exam- ine. Cyprus is an island with a million inhabitants, which joined the Euro- pean Union in 2004 and the Eurozone in 2008. It has a hypertrophied bank- ing sector, apparently due to very large foreign deposits, most notably from Russia. This money was drawn to Cyprus by low taxes and indulgent local authorities. According to statements by officials of the Troika, these Russian deposits include a number of very large individual accounts. Many people therefore imagine that the depositors are oligarchs with fortunes in the tens of millions or even billions of euros—people of the sort one reads about in the magazine rankings. The problem is that neither the European authorities nor the IMF have published any statistics, not even the crudest estimate. Very likely they do not have much information themselves, for the simple reason that they have never equipped themselves with the tools they need to move forward on this issue, even though it is absolutely central. Such opacity is not conducive to a considered and rational resolution of this sort of conflict. The problem is that the Cypriot banks no longer have the money that ap- pears on their balance sheets. Apparently, they invested it in Greek bonds that were since written down and in real estate that is now worthless. Natu- rally, European authorities are hesitant to use the money of European tax- payers to keep the Cypriot banks afloat without some kind of guarantees in return, especially since in the end what they will really be keeping afloat is Russian millionaires.
After months of deliberation, the members of the Troika came up with the disastrous idea of proposing an exceptional tax on all bank deposits with rates of 6.75 percent on deposits up to 100,000 euros and 9.9 percent above that limit. To the extent that this proposal resembles a progressive tax on capital, it might seem intriguing, but there are two important caveats. First, the very limited progressivity of the tax is illusory: in effect, almost the same tax rate is being imposed on small Cypriot savers with accounts of 10,000 euros and on Russian oligarchs with accounts of 10 million euros. Second, the tax base was never precisely defined by the European and international au- thorities handling the matter. The tax seems to apply only to bank deposits as such, so that a depositor could escape it by shifting his or her funds to a bro- kerage account holding stocks or bonds or by investing in real estate or other financial assets. Had this tax been applied, in other words, it would very likely have been extremely regressive, given the composition of the largest portfolios and the opportunities for reallocating investments. After the tax was unani- mously approved by the members of the Troika and the seventeen finance ministers of the Eurozone in March 2013, it was vigorously rejected by the people of Cyprus. In the end, a different solution was adopted: deposits under 100,000 euros were exempted from the tax (this being the ceiling of the de- posit guarantee envisioned under the terms of the proposed European bank- ing union). The exact terms of the new tax remain relatively obscure, however. A bank-by-bank approach seems to have been adopted, although the precise tax rates and bases have not been spelled out explicitly.
This episode is interesting because it illustrates the limits of the central banks and financial authorities. Their strength is that they can act quickly; their weakness is their limited capacity to correctly target the redistributions they cause to occur. The conclusion is that a progressive tax on capital is not only useful as a permanent tax but can also function well as an exceptional levy (with potentially high rates) in the resolution of major banking crises. In the Cypriot case, it is not necessarily shocking that savers were asked to help resolve the crisis, since the country as a whole bears responsibility for the de- velopment strategy chosen by its government. What is deeply shocking, on the other hand, is that the authorities did not even seek to equip themselves with the tools needed to apportion the burden of adjustment in a just, trans- parent, and progressive manner. The good news is that this episode may lead international authorities to recognize the limits of the tools currently at their disposal. If one asks the officials involved why the tax proposed for Cyprus had such little progressivity built into it and was imposed on such a limited base, their immediate response is that the banking data needed to apply a more steeply progressive schedule were not available.24 The bad news is that the authorities seem in no great hurry to resolve the problem, even though the technical solution is within reach. It may be that a progressive tax on capital faces purely ideological obstacles that will take some time to overcome.
The Euro: A Stateless Currency for the Twenty-First Century?
The various crises that have afflicted southern European banks since 2009 raise a more general question, which has to do with the overall architecture of the European Union. How did Europe come to create—for the first time in human history on such a vast scale—a currency without a state? Since Europe’s GDP accounted for nearly one-quarter of global GDP in 2013, the question is of interest not just to inhabitants of the Eurozone but to the entire world.
The usual answer to this question is that the creation of the euro—agreed on in the 1992 Maastricht Treaty in the wake of the fall of the Berlin Wall and the reunification of Germany and made a reality on January 1, 2002, when automatic teller machines across the Eurozone first began to dispense euro notes—is but one step in a lengthy process. Monetary union is supposed to lead naturally to political, fiscal, and budgetary union, to ever closer coop- eration among the member states. Patience is essential, and union must pro- ceed step by step. No doubt this is true to some extent. In my view, however, the unwillingness to lay out a precise path to the desired end—the repeated postponement of any discussion of the itinerary to be followed, the stages along the way, or the ultimate endpoint—may well derail the entire process. If Europe created a stateless currency in 1992, it did so for reasons that were not simply pragmatic. It settled on this institutional arrangement in the late 1980s and early 1990s, at a time when many people believed that the only function of central banking was to control inflation. The “stagflation” of the 1970s had convinced governments and people that central banks ought to be indepen- dent of political control and target low inflation as their only objective. That is why Europe created a currency without a state and a central bank without a government. The crisis of 2008 shattered this static vision of central banking, as it became apparent that in a serious economic crisis central banks have a crucial role to play and that the existing European institutions were wholly unsuited to the task at hand.
Make no mistake. Given the power of central banks to create money in unlimited amounts, it is perfectly legitimate to subject them to rigid con- straints and clear restrictions. No one wants to empower a head of state to re- place university presidents and professors at will, much less to define the con- tent of their teaching. By the same token, there is nothing shocking about imposing tight restrictions on the relations between governments and mone- tary authorities. But the limits of central bank independence should also be precise. In the current crisis, no one, to my knowledge, has proposed that cen- tral banks be returned to the private status they enjoyed in many countries prior to World War I (and in some places as recently as 1945).25 Concretely, the fact that central banks are public institutions means that their leaders are appointed by governments (and in some cases by parliaments). In many cases these leaders cannot be removed for the length of their mandate (usually five or six years) but can be replaced at the end of that term if their policies are deemed inadequate, which provides a measure of political control. In prac- tice, the leaders of the Federal Reserve, the Bank of Japan, and the Bank of England are expected to work hand in hand with the legitimate, demo- cratically elected governments of their countries. In each of these countries, the central bank has in the past played an important role in stabilizing inter- est rates and public debt at low and predictable levels.
The ECB faces a unique set of problems. First, the ECB’s statutes are more restrictive than those of other central banks: the objective of keeping inflation low has absolute priority over the objectives of maintaining growth and full employment. This reflects the ideological context in which the ECB was con- ceived. Furthermore, the ECB is not allowed to purchase newly issued govern- ment debt: it must first allow private banks to lend to the member states of the Eurozone (possibly at a higher rate of interest than that which the ECB charges the private banks) and then purchase the bonds on the secondary market, as it did ultimately, after much hesitation, for the sovereign debt of governments in southern Europe.26 More generally, it is obvious that the ECB’s main difficulty is that it must deal with seventeen separate national debts and seventeen sepa- rate national governments. It is not easy for the bank to play its stabilizing role in such a context. If the Federal Reserve had to choose every morning whether to concentrate on the debt of Wyoming, California, or New York and set its rates and quantities in view of its judgment of the tensions in each particular market and under pressure from each region of the country, it would have a very hard time maintaining a consistent monetary policy.
From the introduction of the euro in 2002 to the onset of the crisis in 2007–2008, interest rates were more or less identical across Europe. No one anticipated the possibility of an exit from the euro, so everything seemed to work well. When the global financial crisis began, however, interest rates be- gan to diverge rapidly. The impact on government budgets was severe. When a government runs a debt close to one year of GDP, a difference of a few points of interest can have considerable consequences. In the face of such uncertainty, it is almost impossible to have a calm democratic debate about the burdens of adjustment or the indispensable reforms of the social state. For the countries of southern Europe, the options were truly impossible. Be- fore joining the euro, they could have devalued their currency, which would at least have restored competitiveness and spurred economic activity. Specula- tion on national interest rates was in some ways more destabilizing than the previous speculation on exchange rates among European currencies, particu- larly since crossborder bank lending had meanwhile grown to such proportions that panic on the part of a handful of market actors was enough to trigger capital flows large enough to seriously affect countries such as Greece, Portugal, and Ireland, and even larger countries such as Spain and Italy. Logically, such a loss of monetary sovereignty should have been compensated by guaranteeing that countries could borrow if need be at low and predictable rates.
The Question of European Unification
The only way to overcome these contradictions is for the countries of the Eu- rozone (or at any rate those who are willing) to pool their public debts. The German proposal to create a “redemption fund,” which I touched on earlier, is a good starting point, but it lacks a political component.27 Concretely, it is impossible to decide twenty years in advance what the exact pace of “redemp- tion” will be—that is, how quickly the stock of pooled debt will be reduced to the target level. Many parameters will affect the outcome, starting with the state of the economy. To decide how quickly to pay down the pooled debt, or, in other words, to decide how much public debt the Eurozone should carry, one would need to empower a European “budgetary parliament” to decide on a European budget. The best way to do this would be to draw the members of this parliament from the ranks of the national parliaments, so that European parliamentary sovereignty would rest on the legitimacy of democratically elected national assemblies.28 Like any other parliament, this body would de- cide issues by majority vote after open public debate. Coalitions would form, based partly on political affiliation and partly on national affiliation. The de- cisions of such a body will never be ideal, but at least we would know what had been decided and why, which is important. It is preferable, I think, to create such a new body rather than rely on the current European Parliament, which is composed of members from twenty-seven states (many of which do not belong to the Eurozone and do not wish to pursue further European inte- gration at this time). To rely on the existing European Parliament would also conflict too overtly with the sovereignty of national parliaments, which would be problematic in regard to decisions affecting national budget deficits. That is probably the reason why transfers of power to the European Parliament have always been quite limited in the past and will likely remain so for quite some time. It is time to accept this fact and to create a new parliamentary body to reflect the desire for unification that exists within the Eurozone countries (as indicated most clearly by their agreement to relinquish monetary sover- eignty with due regard for the consequences).
Several institutional arrangements are possible. In the spring of 2013, the new Italian government pledged to support a proposal made a few years earlier by German authorities concerning the election by universal suffrage of a president of the European Union—a proposal that logically ought to be accompanied by a broadening of the president’s powers. If a budgetary parliament decides what the Eurozone’s debt ought to be, then there clearly needs to be a European finance minister responsible to that body and charged with proposing a Eurozone budget and annual deficit. What is certain is that the Eurozone cannot do without a genuine parliamentary chamber in which to set its budgetary strategy in a public, democratic, and sovereign manner, and more generally to discuss ways to overcome the financial and banking crisis in which Europe currently finds itself mired. The existing European councils of heads of state and finance ministers cannot do the work of this budgetary body. They meet in secret, do not engage in open public debate, and regularly end their meetings with triumphal midnight communiqués announcing that Europe has been saved, even though the participants them- selves do not always seem to be sure about what they have decided. The deci- sion on the Cypriot tax is typical in this regard: although it was approved unanimously, no one wanted to accept responsibility in public.29 This type of proceeding is worthy of the Congress of Vienna (1815) but has no place in the Europe of the twenty-first century. The German and Italian proposals alluded to above show that progress is possible. It is nevertheless striking to note that France has been mostly absent from this debate through two presidencies,30 even though the country is prompt to lecture others about European solidar- ity and the need for debt mutualization (at least at the rhetorical level).31
Unless things change in the direction I have indicated, it is very difficult to imagine a lasting solution to the crisis of the Eurozone. In addition to pool- ing debts and deficits, there are of course other fiscal and budgetary tools that no country can use on its own, so that it would make sense to think about using them jointly. The first example that comes to mind is of course the pro- gressive tax on capital.
An even more obvious example is a tax on corporate profits. Tax competi- tion among European states has been fierce in this respect since the early 1990s. In particular, several small countries, with Ireland leading the way, followed by several Eastern European countries, made low corporate taxes a key element of their economic development strategies. In an ideal tax system, based on shared and reliable bank data, the corporate tax would play a limited role. It would simply be a form of withholding on the income tax (or capital tax) due from individual shareholders and bondholders.32 In practice, the problem is that this “withholding” tax is often the only tax paid, since much of what corporations declare as profit does not figure in the taxable income of individual shareholders, which is why it is important to collect a significant amount of tax at the source through the corporate tax.

The right approach would be to require corporations to make a single dec- laration of their profits at the European level and then tax that profit in a way that is less subject to manipulation than is the current system of taxing the profits of each subsidiary individually. The problem with the current system is that multinational corporations often end up paying ridiculously small amounts because they can assign all their profits artificially to a subsidiary located in a place where taxes are very low; such a practice is not illegal, and in the minds of many corporate managers it is not even unethical.33 It makes more sense to give up the idea that profits can be pinned down to a particular state or territory; instead, one can apportion the revenues of the corporate tax on the basis of sales or wages paid within each country.
A related problem arises in connection with the tax on individual capital. The general principle on which most tax systems are based is the principle of residence: each country taxes the income and wealth of individuals who re- side within its borders for more than six months a year. This principle is in- creasingly difficult to apply in Europe, especially in border areas (for example, along the Franco-Belgian border). What is more, wealth has always been taxed partly as a function of the location of the asset rather than of its owner. For example, the owner of a Paris apartment must pay property tax to the city of Paris, even if he lives halfway around the world and regardless of his na- tionality. The same principle applies to the wealth tax, but only in regard to real estate. There is no reason why it could not also be applied to financial as- sets, based on the location of the corresponding business activity or company. The same is true for government bonds. Extending the principle of “residence of the capital asset” (rather than of its owner) to financial assets would obvi- ously require automatic sharing of bank data to allow the tax authorities to assess complex ownership structures. Such a tax would also raise the issue of multinationality.34 Adequate answers to all these questions can clearly be found only at the European (or global) level. The right approach is therefore to create a Eurozone budgetary parliament to deal with them.
Are all these proposals utopian? No more so than attempting to create a stateless currency. When countries relinquish monetary sovereignty, it is es- sential to restore their fiscal sovereignty over matters no longer within the purview of the nation-state, such as the interest rate on public debt, the pro- gressive tax on capital, or the taxation of multinational corporations. For the countries of Europe, the priority now should be to construct a continental po- litical authority capable of reasserting control over patrimonial capitalism and private interests and of advancing the European social model in the twenty- first century. The minor disparities between national social models are of secondary importance in view of the challenges to the very survival of the common European model.35
Another point to bear in mind is that without such a European political union, it is highly likely that tax competition will continue to wreak havoc. The race to the bottom continues in regard to corporate taxes, as recently pro- posed “allowances for corporate equity” show.36 It is important to realize that tax competition regularly leads to a reliance on consumption taxes, that is, to the kind of tax system that existed in the nineteenth century, where no pro- gressivity is possible. In practice, this favors individuals who are able to save, to change their country of residence, or both.37 Note, however, that progress toward some forms of fiscal cooperation has been more rapid than one might imagine at first glance: consider, for example, the proposed financial transac- tions tax, which could become one of the first truly European taxes. Although such a tax is far less significant than a tax on capital or corporate profits (in terms of both revenues and distributive impact), recent progress on this tax shows that nothing is foreordained.38 Political and fiscal history always blaze their own trails.
Government and Capital Accumulation in the Twenty-First Century
Let me now take a step back from the immediate issues of European con- struction and raise the following question: In an ideal society, what level of public debt is desirable? Let me say at once that there is no certainty about the answer, and only democratic deliberation can decide, in keeping with the goals each society sets for itself and the particular challenges each country faces. What is certain is that no sensible answer is possible unless a broader question is also raised: What level of public capital is desirable, and what is the ideal level of total national capital?
In this book, I have looked in considerable detail at the evolution of the capital/income ratio β across space and time. I have also examined how β is determined in the long run by the savings and growth rates of each country, according to the law β = s /g. But I have not yet asked what β is desirable. In an ideal society, should the capital stock be equal to five years of national income, or ten years, or twenty? How should we think about this question? It is im- possible to give a precise answer. Under certain hypotheses, however, one can establish a ceiling on the quantity of capital that one can envision accumulat- ing a priori. The maximal level of capital is attained when so much has been accumulated that the return on capital, r, supposed to be equal to its marginal productivity, falls to be equal to the growth rate g. In 1961 Edmund Phelps baptized the equality r = g the “golden rule of capital accumulation.” If one takes it literally, the golden rule implies much higher capital/income ratios than have been observed historically, since, as I have shown, the return on capital has always been significantly higher than the growth rate. Indeed, r was much greater than g before the nineteenth century (with a return on capi- tal of 4–5 percent and a growth rate below 1 percent), and it will probably be so again in the twenty-first century (with a return of 4–5 percent once again and long-term growth not much above 1.5 percent).39 It is very difficult to say what quantity of capital would have to be accumulated for the rate of return to fall to 1 or 1.5 percent. It is surely far more than the six to seven years of national income currently observed in the most capital-intensive countries. Perhaps it would take ten to fifteen years of national income, maybe even more. It is even harder to imagine what it would take for the return on capital to fall to the low growth levels observed before the eighteenth century (less than 0.2 percent). One might need to accumulate capital equivalent to twenty to thirty years of national income: everyone would then own so much real estate, machinery, tools, and so on that an additional unit of capital would add less than 0.2 percent to each year’s output.
The truth is that to pose the question in this way is to approach it too ab- stractly. The answer given by the golden rule is not very useful in practice. It is unlikely that any human society will ever accumulate that much capital. Nev- ertheless, the logic that underlies the golden rule is not without interest. Let me summarize the argument briefly.40 If the golden rule is satisfied, so r = g, then by definition capital’s long-run share of national income is exactly equal to the savings rate: α = s. Conversely, as long as r > g, capital’s long-run share is greater than the savings rate: α > s.41 In other words, in order for the golden rule to be satisfied, one has to have accumulated so much capital that capital no longer yields anything. Or, more precisely, one has to have accumulated so much capital that merely maintaining the capital stock at the same level (in proportion to national income) requires reinvesting all of the return to capital every year. That is what α = s means: all of the return to capital must be saved and added back to the capital stock. Conversely, if r > g, than capital returns something in the long run, in the sense that it is no longer necessary to rein- vest all of the return on capital to maintain the same capital/income ratio.
Clearly, then, the golden rule is related to a “capital saturation” strategy. So much capital is accumulated that rentiers have nothing left to consume, since they must reinvest all of their return if they want their capital to grow at the same rate as the economy, thereby preserving their social status relative to the average for the society. Conversely, if r > g, it suffices to reinvest a fraction of the return on capital equal to the growth rate ( g) and to consume the rest (r − g). The inequality r > g is the basis of a society of rentiers. Accumulating enough capital to reduce the return to the growth rate can therefore end the reign of the rentier.
But is it the best way to achieve that end? Why would the owners of capi- tal, or society as a whole, choose to accumulate that much capital? Bear in mind that the argument that leads to the golden rule simply sets an upper limit but in no way justifies reaching it.42 In practice, there are much simpler and more effective ways to deal with rentiers, namely, by taxing them: no need to accumulate capital worth dozens of years of national income, which might require several generations to forgo consumption.43 At a purely theoretical level, everything depends in principle on the origins of growth. If there is no productivity growth, so that the only source of growth is demographic, then accumulating capital to the level required by the golden rule might make sense. For example, if one assumes that the population will grow forever at 1 percent a year and that people are infinitely patient and altruistic toward fu- ture generations, then the right way to maximize per capita consumption in the long run is to accumulate so much capital that the rate of return falls to 1 percent. But the limits of this argument are obvious. In the first place, it is rather odd to assume that demographic growth is eternal, since it depends on the reproductive choices of future generations, for which the present genera- tion is not responsible (unless we imagine a world with a particularly under- developed contraceptive technology). Furthermore, if demographic growth is also zero, one would have to accumulate an infinite quantity of capital: as long as the return on capital is even slightly positive, it will be in the interest
of future generations for the present generation to consume nothing and ac- cumulate as much as possible. According to Marx, who implicitly assumes zero demographic and productivity growth, this is the ultimate consequence of the capitalist’s unlimited desire to accumulate more and more capital, and in the end it leads to the downfall of capitalism and the collective appropria- tion of the means of production. Indeed, in the Soviet Union, the state claimed to serve the common good by accumulating unlimited industrial capital and ever-increasing numbers of machines: no one really knew where the planners thought accumulation should end.44
If productivity growth is even slightly positive, the process of capital ac- cumulation is described by the law β = s/g. The question of the social opti- mum then becomes more difficult to resolve. If one knows in advance that productivity will increase forever by 1 percent a year, it follows that future generations will be more productive and prosperous than present ones. That being the case, is it reasonable to sacrifice present consumption to the accu- mulation of vast amounts of capital? Depending on how one chooses to com- pare and weigh the well-being of different generations, one can reach any de- sired conclusion: that it is wiser to leave nothing at all for future generations (except perhaps our pollution), or to abide by the golden rule, or any other split between present and future consumption between those two extremes. Clearly, the golden rule is of limited practical utility.45
In truth, simple common sense should have been enough to conclude that no mathematical formula will enable us to resolve the complex issue of decid- ing how much to leave for future generations. Why, then, did I feel it necessary to present these conceptual debates around the golden rule? Because they have had a certain impact on public debate in recent years in regard first to Euro- pean deficits and second to controversies around the issue of climate change.
Law and Politics
First, a rather different idea of “the golden rule” has figured in the European debate about public deficits.46 In 1992, when the Treaty of Maastricht created the euro, it was stipulated that member states should ensure that their budget deficits would be less than 3 percent of GDP and that total public debt would remain below 60 percent of GDP.47 The precise economic logic behind these choices has never been completely explained.48 Indeed, if one does not include public assets and total national capital, it is difficult to justify any particular level of public debt on rational grounds. I have already mentioned the real reason for these strict budgetary constraints, which are historically unprece- dented. (The United States, Britain, and Japan have never imposed such rules on themselves.) It is an almost inevitable consequence of the decision to create a common currency without a state, and in particular without pooling the debt of member states or coordinating deficits. Presumably, the Maastricht criteria would become unnecessary if the Eurozone were to equip itself with a budgetary parliament empowered to decide and coordinate deficit levels for the various member states. The decision would then be a sovereign and demo- cratic one. There is no convincing reason to impose a priori constraints, much less to enshrine limits on debts and deficits in state constitutions. Since the construction of a budgetary union has only just begun, of course, special rules may be necessary to build confidence: for example, one can imagine requiring a parliamentary supermajority in order to exceed a certain level of debt. But there is no justification for engraving untouchable debt and deficit limits in stone in order to thwart future political majorities.
Make no mistake: I have no particular liking for public debt. As I noted earlier, debt often becomes a backhanded form of redistribution of wealth from the poor to the rich, from people with modest savings to those with the means to lend to the government (who as a general rule ought to be paying taxes rather than lending). Since the middle of the twentieth century and the large-scale public debt repudiations (and debt shrinkage through inflation) after World War II, many dangerous illusions have arisen in regard to govern- ment debt and its relation to social redistribution. These illusions urgently need to be dispelled.
There are nevertheless a number of reasons why it is not very judicious to enshrine budgetary restrictions in statutory or constitutional stone. For one thing, historical experience suggests that in a serious crisis it is often necessary to make emergency budget decisions on a scale that would have been un- imaginable before the crisis. To leave it to a constitutional judge (or commit- tee of experts) to judge such decisions case by case is to take a step back from democracy. In any case, turning the power to decide over to the courts is not without risk. Indeed, history shows that constitutional judges have an unfor- tunate tendency to interpret fiscal and budgetary laws in very conservative ways.49 Such judicial conservatism is particularly dangerous in Europe, where there has been a tendency to see the free circulation of people, goods, and capital as fundamental rights with priority over the right of member states to promote the general interest of their people, if need be by levying taxes.
Finally, it is impossible to judge the appropriate level of debts and deficits without taking into account numerous other factors affecting national wealth. When we look at all the available data today, what is most striking is that na- tional wealth in Europe has never been so high. To be sure, net public wealth is virtually zero, given the size of the public debt, but net private wealth is so high that the sum of the two is as great as it has been in a century. Hence the idea that we are about to bequeath a shameful burden of debt to our children and grandchildren and that we ought to wear sackcloth and ashes and beg for forgiveness simply makes no sense. The nations of Europe have never been so rich. What is true and shameful, on the other hand, is that this vast national wealth is very unequally distributed. Private wealth rests on public poverty, and one particularly unfortunate consequence of this is that we currently spend far more in interest on the debt than we invest in higher education. This has been true, moreover, for a very long time: because growth has been fairly slow since 1970, we are in a period of history in which debt weighs very heavily on our public finances.50 This is the main reason why the debt must be reduced as quickly as possible, ideally by means of a progressive one-time tax on private capital or, failing that, by inflation. In any event, the decision should be made by a sovereign parliament after democratic debate.51
Climate Change and Public Capital
The second important issue on which these golden rule–related questions have a major impact is climate change and, more generally, the possibility of deterioration of humanity’s natural capital in the century ahead. If we take a global view, then this is clearly the world’s principal long-term worry. The Stern Report, published in 2006, calculated that the potential damage to the environment by the end of the century could amount, in some scenarios, to dozens of points of global GDP per year. Among economists, the controversy surrounding the report hinged mainly on the question of the rate at which future damage to the environment should be discounted. Nicholas Stern, who is British, argued for a relatively low discount rate, approximately the same as the growth rate (1–1.5 percent a year). With that assumption, present generations weigh future damage very heavily in their own calculations. Wil- liam Nordhaus, an American, argued that one ought to choose a discount rate closer to the average return on capital (4–4.5 percent a year), a choice that makes future disasters seem much less worrisome. In other words, even if everyone agrees about the cost of future disasters (despite the obvious uncertainties), they can reach different conclusions. For Stern, the loss of global well-being is so great that it justifies spending at least 5 points of global GDP a year right now to attempt to mitigate climate change in the future. For Nordhaus, such a large expenditure would be entirely unreasonable, because future genera- tions will be richer and more productive than we are. They will find a way to cope, even if it means consuming less, which will in any case be less costly from the standpoint of universal well-being than making the kind of effort Stern envisions. So in the end, all of these expert calculations come down to a stark difference of opinion.
Stern’s opinion seems more reasonable to me than Nordhaus’s, whose op- timism is attractive, to be sure, as well as opportunely consistent with the US strategy of unrestricted carbon emissions, but ultimately not very convinc- ing.52 In any case, this relatively abstract debate about discount rates largely sidesteps what seems to me the central issue. Public debate, especially in Eu- rope but also in China and the United States, has taken an increasingly prag- matic turn, with discussion of the need for major investment in the search for new nonpolluting technologies and forms of renewable energy sufficiently abundant to enable the world to do without hydrocarbons. Discussion of “ecological stimulus” is especially prevalent in Europe, where many people see it as a possible way out of today’s dismal economic climate. This strategy is particularly tempting because many governments are currently able to bor- row at very low interest rates. If private investors are unwilling to spend and invest, then why shouldn’t governments invest in the future to avoid a likely degradation of natural capital?53
This is a very important debate for the decades ahead. The public debt (which is much smaller than total private wealth and perhaps not really that difficult to eliminate) is not our major worry. The more urgent need is to in- crease our educational capital and prevent the degradation of our natural capital. This is a far more serious and difficult challenge, because climate change cannot be eliminated at the stroke of a pen (or with a tax on capital, which comes to the same thing). The key practical issue is the following. Suppose that Stern is approximately correct that there is good reason to spend the equivalent of 5 percent of global GDP annually to ward off an environmental catastrophe. Do we really know what we ought to invest in and how we should organize our effort? If we are talking about public investments of this magnitude, it is important to realize that this would represent public spend- ing on a vast scale, far vaster than any previous public spending by the rich countries.54 If we are talking about private investment, we need to be clear about the manner of public financing and who will own the resulting tech- nologies and patents. Should we count on advanced research to make rapid progress in developing renewable energy sources, or should we immediately subject ourselves to strict limits on hydrocarbon consumption? It would prob- ably be wise to choose a balanced strategy that would make use of all available tools.55 So much for common sense. But the fact remains that no one knows for now how these challenges will be met or what role governments will play in preventing the degradation of our natural capital in the years ahead.
Economic Transparency and Democratic Control of Capital
More generally, it is important, I think, to insist that one of the most impor- tant issues in coming years will be the development of new forms of property and democratic control of capital. The dividing line between public capital and private capital is by no means as clear as some have believed since the fall of the Berlin Wall. As noted, there are already many areas, such as education, health, culture, and the media, in which the dominant forms of organization and ownership have little to do with the polar paradigms of purely private capital (modeled on the joint-stock company entirely owned by its sharehold- ers) and purely public capital (based on a similar top-down logic in which the sovereign government decides on all investments). There are obviously many intermediate forms of organization capable of mobilizing the talent of different individuals and the information at their disposal. When it comes to organizing collective decisions, the market and the ballot box are merely two polar ex- tremes. New forms of participation and governance remain to be invented.56
The essential point is that these various forms of democratic control of capital depend in large part on the availability of economic information to each of the involved parties. Economic and financial transparency are impor- tant for tax purposes, to be sure, but also for much more general reasons. They are essential for democratic governance and participation. In this respect, what matters is not transparency regarding individual income and wealth, which is of no intrinsic interest (except perhaps in the case of political officials or in situations where there is no other way to establish trust).57 For collective action, what would matter most would be the publication of detailed ac- counts of private corporations (as well as government agencies). The account- ing data that companies are currently required to publish are entirely inade- quate for allowing workers or ordinary citizens to form an opinion about corporate decisions, much less to intervene in them. For example, to take a concrete case mentioned at the very beginning of this book, the published ac- counts of Lonmin, Inc., the owner of the Marikana platinum mine where thirty-four strikers were shot dead in August 2012, do not tell us precisely how the wealth produced by the mine is divided between profits and wages. This is generally true of published corporate accounts around the world: the data are grouped in very broad statistical categories that reveal as little as pos- sible about what is actually at stake, while more detailed information is re- served for investors.58 It is then easy to say that workers and their representa- tives are insufficiently informed about the economic realities facing the firm to participate in investment decisions. Without real accounting and financial transparency and sharing of information, there can be no economic democ- racy. Conversely, without a real right to intervene in corporate decision-making (including seats for workers on the company’s board of directors), transparency is of little use. Information must support democratic institutions; it is not an end in itself. If democracy is someday to regain control of capitalism, it must start by recognizing that the concrete institutions in which democracy and capitalism are embodied need to be reinvented again and again.







